import {useEffect,useState} from 'react';
import {toast} from 'sonner';
import {foodOperations} from '@/lib/foodOperations';
import ImageUpload from '@/components/ImageUpload';
import {checkoutConfig,type CheckoutConfiguration} from './PreorderFields';
import PickupCard from './PickupCard';
export default function CheckoutSettings(){const [data,setData]=useState<CheckoutConfiguration|null>(null),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState(''),[closedDraft,setClosedDraft]=useState('');useEffect(()=>{void checkoutConfig().then(next=>{setData(next);setClosedDraft((next.policy.closed_dates||[]).join(', '));}).catch(e=>setError(e.message));},[]);if(!data)return <p role="status">{error||'Загрузка настроек…'}</p>;
 async function save(){if(!data||busy)return;setBusy(true);try{const next=await foodOperations<CheckoutConfiguration>('','PUT',{...data.policy,closed_dates:closedDraft.split(',').map(x=>x.trim()).filter(Boolean),pickup:{display_name:data.pickup.display_name,address:data.pickup.address,instructions:data.pickup.instructions,photo:data.pickup.photo,latitude:data.pickup.latitude,longitude:data.pickup.longitude,supports_pickup:data.pickup.supports_pickup!==false,supports_delivery:data.pickup.supports_delivery!==false}},'checkout-config');setData(next);toast.success('Предзаказы и самовывоз сохранены');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 return <section className="space-y-4 rounded-xl border bg-card p-4"><h2 className="text-lg font-bold">Предзаказы и точка самовывоза</h2><p className="text-sm text-muted-foreground">Часы работы: {data.working_hours||'не заданы'}. Используется общее расписание заведения.</p><label className="flex gap-2"><input type="checkbox" checked={data.policy.enabled} onChange={e=>setData({...data,policy:{...data.policy,enabled:e.target.checked}})}/>Принимать предзаказы</label><div className="grid gap-3 sm:grid-cols-2">{([['min_minutes','Минимум до получения, минут'],['advance_days','На сколько дней вперёд'],['step_minutes','Шаг времени, минут'],['prepare_minutes','Начинать подготовку за, минут']] as const).map(([key,label])=><label key={key} className="text-sm">{label}<input type="number" min="0" className="mt-1 w-full rounded-lg border bg-background p-3" value={data.policy[key]} onChange={e=>setData({...data,policy:{...data.policy,[key]:Number(e.target.value)}})}/></label>)}</div>
 <label className="block text-sm">Не принимать предзаказы в эти даты (ГГГГ-ММ-ДД, через запятую)<input aria-label="Закрытые даты" className="mt-1 w-full rounded-lg border bg-background p-3" value={closedDraft} onChange={e=>setClosedDraft(e.target.value)}/></label>
 {(['supports_pickup','supports_delivery'] as const).map((key,i)=><label key={key} className="flex gap-2 text-sm"><input type="checkbox" checked={data.pickup[key]!==false} onChange={e=>setData({...data,pickup:{...data.pickup,[key]:e.target.checked}})}/>{i?'Доставка доступна':'Самовывоз доступен'}</label>)}
 {(['display_name','address','instructions'] as const).map((key,i)=><label className="block text-sm" key={key}>{['Название точки','Адрес / место','Ориентир и инструкция'][i]}<input className="mt-1 w-full rounded-lg border bg-background p-3" value={data.pickup[key]} onChange={e=>setData({...data,pickup:{...data.pickup,[key]:e.target.value}})}/></label>)}
 <ImageUpload value={data.pickup.photo} onChange={photo=>setData({...data,pickup:{...data.pickup,photo}})} onUploadingChange={setUploading} folder="dam-pickup"/>
 <div className="grid grid-cols-2 gap-3">{(['latitude','longitude'] as const).map((key,i)=><label className="text-sm" key={key}>{i?'Долгота':'Широта'}<input type="number" step="any" className="mt-1 w-full rounded-lg border bg-background p-3" value={data.pickup[key]??''} onChange={e=>setData({...data,pickup:{...data.pickup,[key]:e.target.value===''?null:Number(e.target.value)}})}/></label>)}</div><button type="button" className="rounded-lg border px-4 py-3 text-sm" onClick={()=>navigator.geolocation.getCurrentPosition(p=>setData({...data,pickup:{...data.pickup,latitude:p.coords.latitude,longitude:p.coords.longitude}}),()=>toast.error('Не удалось определить точку. Введите координаты из карты.'))}>Я на точке — определить координаты</button><p className="text-xs text-muted-foreground">Указывайте координаты входа, находясь у точки. Можно скопировать широту и долготу из карты. Проверьте маршрут в предварительном просмотре.</p><PickupCard location={data.pickup}/><button type="button" disabled={busy||uploading} onClick={()=>void save()} className="rounded-xl bg-primary px-5 py-3 font-semibold text-primary-foreground disabled:opacity-50">{busy?'Сохраняем…':'Сохранить предзаказы и самовывоз'}</button></section>;
}
