import { useCallback, useEffect, useRef, useState } from 'react';
import { foodBusiness } from '@/lib/foodOperations';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { clockTime, staffName, type OwnerOverview } from '@/pages/DamOwnerDashboard';
type Courier = {id:string; name:string; phone:string; active:boolean; pin_set:boolean};
export default function DamCourierTeam({overview}:{overview:OwnerOverview|null}) {
  const [rows,setRows]=useState<Courier[]>([]), [error,setError]=useState(''), [notice,setNotice]=useState('');
  const [busy,setBusy]=useState(false), [editing,setEditing]=useState<string|null>(null);
  const [form,setForm]=useState({name:'',phone:'',pin:''}), [edit,setEdit]=useState({name:'',pin:''});
  const lock=useRef(false);
  const load=useCallback(async()=>{try{setRows(await foodBusiness<Courier[]>('/staff/couriers'));}catch(e){setError((e as Error).message);}},[]);
  useEffect(()=>{void load();},[load,overview]);
  async function save(path:string,method:string,body?:unknown){if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{await foodBusiness(path,method,body);setEditing(null);setEdit({name:'',pin:''});setNotice('Изменения сохранены');await load();if(method==='POST')setForm({name:'',phone:'',pin:''});}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}}
  return <section className="space-y-3"><div><h4 className="text-lg font-semibold">Курьеры</h4><p className="text-sm text-muted-foreground">Отдельный вход по персональному PIN. История доставок сохраняется.</p><a href="/food/courier" target="_blank" rel="noopener noreferrer" className="text-sm underline">Открыть кабинет курьера →</a></div>
    {error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>}{notice&&<p role="status" className="text-sm text-emerald-700">{notice}</p>}
    {rows.map(row=>{const member=overview?.team.find(p=>p.type==='courier'&&p.id===row.id);return <article key={row.id} className="rounded-2xl border bg-card p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><strong>{staffName(row.name,row.phone)}</strong><p className="text-sm text-muted-foreground">{row.phone} · Курьер · {row.active?'Доступ включён':'Доступ отключён'}</p><p className="text-xs text-muted-foreground">{member?.shift?`На смене с ${clockTime(member.shift.opened_at)}`:'Не на смене'}{!row.pin_set?' · PIN не назначен':''}</p>{!!member?.deliveries.length&&<p className="text-xs">Доставки: {member.deliveries.map(id=>`№${id}`).join(', ')}</p>}</div><Button variant="outline" size="sm" onClick={()=>{setEditing(editing===row.id?null:row.id);setEdit({name:row.name,pin:''});}}>Настройки доступа</Button></div>{editing===row.id&&<fieldset disabled={busy} className="mt-4 space-y-3 border-t pt-3"><label className="block text-sm">Имя сотрудника<Input value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><label className="block text-sm">Новый PIN (если меняете)<Input type="password" inputMode="numeric" maxLength={4} value={edit.pin} onChange={e=>setEdit({...edit,pin:e.target.value.replace(/\D/g,'')})}/></label><div className="flex flex-wrap gap-2"><Button onClick={()=>void save(`/staff/couriers/${row.id}`,'PATCH',{name:edit.name,...(edit.pin?{pin:edit.pin}:{})})}>Сохранить</Button><Button variant="outline" onClick={()=>void save(`/staff/couriers/${row.id}`,'PATCH',{active:!row.active})}>{row.active?'Отключить доступ':'Включить доступ'}</Button></div><details className="border-t pt-3"><summary className="cursor-pointer text-sm text-muted-foreground">Опасная зона</summary><Button variant="destructive" className="mt-3" onClick={()=>{if(window.confirm(`Удалить доступ ${row.name}? Вход будет закрыт, история доставок и действий сохранится.`))void save(`/staff/couriers/${row.id}`,'DELETE');}}>Удалить доступ</Button></details></fieldset>}</article>;})}
    <details className="rounded-2xl border bg-card p-4"><summary className="cursor-pointer font-semibold">Добавить курьера</summary><fieldset disabled={busy} className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm">Имя курьера<Input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="text-sm">Телефон +7…<Input inputMode="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label className="text-sm">PIN из 4 цифр<Input type="password" inputMode="numeric" maxLength={4} value={form.pin} onChange={e=>setForm({...form,pin:e.target.value.replace(/\D/g,'')})}/></label><Button onClick={()=>void save('/staff/couriers','POST',form)}>Создать доступ курьера</Button></fieldset></details>
  </section>;
}
