import {useEffect, useRef, useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import ImageUpload from '@/components/ImageUpload';
import {toast} from 'sonner';
import {invalidateAllCaches} from '@/lib/cache';
import {bumpFoodMenuVersion} from '@/lib/foodCartStorage';
import {ownerMenu,menuMoney,type MenuCatalog,type MenuProduct,type ModifierGroup,type Combo,type Component} from '@/lib/damMenu';
import MenuSelectionDialog from './MenuSelection';

type GroupDraft=Omit<ModifierGroup,'id'> & {id?:number};
type ItemDraft=Omit<MenuProduct,'id'> & {id?:number};
const checkbox=(label:string,value:boolean,onChange:(x:boolean)=>void)=><label className="flex min-h-11 items-center gap-3"><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/>{label}</label>;
const numberInput=(label:string,value:number,onChange:(n:number)=>void,min=0)=><label className="block text-sm">{label}<Input type="number" min={min} step="any" value={Number.isFinite(value)?value:''} onChange={e=>onChange(Number(e.target.value))}/></label>;

export default function OwnerMenu({mode='items'}:{mode?:'items'|'combos'|'modifiers'}) {
  const [catalog,setCatalog]=useState<MenuCatalog|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [search,setSearch]=useState(''),[showArchive,setShowArchive]=useState(false);
  const [item,setItem]=useState<ItemDraft|null>(null),[group,setGroup]=useState<GroupDraft|null>(null),[preview,setPreview]=useState<MenuProduct|null>(null);
  async function load(){try{setCatalog(await ownerMenu<MenuCatalog>('/manage'));setError('');}catch(e){setError((e as Error).message);}}
  useEffect(()=>{void load();},[]);
  const saveLock=useRef(false);
  async function save(){
    if(saveLock.current)return;
    if(group && (group.min_select>group.max_select || group.min_select<0 || group.max_select<1 || !Number.isInteger(group.max_select) || !Number.isInteger(group.min_select))) {setError('Проверьте минимум и максимум выборов');return;}
    if(item?.is_combo) {
      const recipe=item.combo_config;
      if(!recipe || (!recipe.components.length && !recipe.groups.length) || recipe.components.some(p=>!p.item_id || !Number.isInteger(p.quantity) || p.quantity<1) || recipe.groups.some(g=>!g.name.trim() || !g.options.length || g.min_select>g.max_select || g.max_select>g.options.length || g.options.some(p=>!p.item_id || !Number.isInteger(p.quantity) || p.quantity<1 || Number(p.surcharge)<0))) {setError('Заполните состав и проверьте варианты выбора комбо');return;}
    }
    saveLock.current=true;setBusy(true);setError('');
    try{
      if(group){
        await ownerMenu(`/groups${group.id?'/'+group.id:''}`,group.id?'PUT':'POST',{
          name:group.name,type:group.type,is_active:group.is_active!==false,archived:!!group.archived_at,is_required:group.is_required,min_select:group.min_select,max_select:group.max_select,sort_order:group.sort_order || 0,expected_version:group.menu_version,
          options:group.options.map(o=>({id:o.id>0?o.id:undefined,name:o.name,price:Number(o.price),is_active:o.is_active!==false,archived:!!o.archived_at,sort_order:o.sort_order || 0}))});
      } else if(item){
        await ownerMenu(`/items${item.id?'/'+item.id:''}`,item.id?'PUT':'POST',{
          name:item.name,description:item.description || '',price:Number(item.price),image_url:item.image_url || '',category_id:item.category_id || null,is_active:item.is_active!==false,available:item.available!==false,is_popular:!!item.is_popular,weight:item.weight || '',sort_order:item.sort_order || 0,archived:!!item.archived_at,is_combo:!!item.is_combo,combo_config:item.is_combo?item.combo_config:null,modifiers_enabled:!!item.modifiers_enabled,modifier_group_ids:item.modifier_group_ids || [],expected_version:item.menu_version});
      }
      invalidateAllCaches();bumpFoodMenuVersion();toast.success('Меню сохранено');setGroup(null);setItem(null);await load();
    }catch(e){setError((e as Error).message);}finally{saveLock.current=false;setBusy(false);}
  }
  function newItem(){setError('');setItem({name:'',price:0,is_active:true,available:true,is_combo:mode==='combos',combo_config:mode==='combos'?{components:[],groups:[]}:null,modifiers_enabled:false,modifier_group_ids:[],sort_order:catalog?.products.length || 0});}
  function newGroup(){setError('');setGroup({name:'',type:'multiple',is_required:false,min_select:0,max_select:3,is_active:true,options:[],sort_order:catalog?.groups.length || 0});}
  const basic=(catalog?.products || []).filter(p=>!p.is_combo && !p.archived_at);
  const recipe:Combo=item?.combo_config || {components:[],groups:[]};
  function changeRecipe(next:Combo){if(item)setItem({...item,combo_config:next});}
  function selectDish(value:number,onChange:(id:number)=>void){return <select aria-label="Блюдо в составе" className="min-h-11 w-full rounded-lg border bg-background p-2" value={value || ''} onChange={e=>onChange(Number(e.target.value))}><option value="">Выберите блюдо</option>{basic.map(p=><option key={p.id} value={p.id}>{p.name}{p.is_active===false || p.available===false?' — недоступно':''}</option>)}</select>;}
  function partRow(p:Component,i:number,change:(p:Component)=>void,remove:()=>void,choice=false){return <div key={i} className="grid grid-cols-2 gap-3 rounded-xl border p-3 sm:grid-cols-[1fr_90px_110px_auto]"><div className="col-span-2 sm:col-span-1">{selectDish(p.item_id,id=>change({...p,item_id:id}))}</div>{numberInput('Количество',p.quantity,n=>change({...p,quantity:n}),1)}{choice?numberInput('Доплата, ₸',Number(p.surcharge || 0),n=>change({...p,surcharge:n})):<span/>}<Button type="button" variant="ghost" onClick={remove}>Убрать</Button></div>;}
  function showPreview(){
    if(!item)return;
    const config=item.combo_config;
    setPreview({...item,id:item.id || -1,price:Number(item.price),sellable:true,
      modifier_groups:(catalog?.groups || []).filter(g=>item.modifier_group_ids?.includes(g.id)),
      combo:config?{components:config.components.map(p=>({...p,name:basic.find(x=>x.id===p.item_id)?.name || 'Выберите блюдо'})),groups:config.groups.map(g=>({...g,options:g.options.map(p=>({...p,name:basic.find(x=>x.id===p.item_id)?.name || 'Выберите блюдо',available:true}))}))}:null});
  }
  const title=mode==='modifiers'?'Добавки':mode==='combos'?'Комбо':'Блюда';
  const rows=(catalog?.products || []).filter(p=>(mode==='combos'?p.is_combo:!p.is_combo) && (showArchive || !p.archived_at) && p.name.toLowerCase().includes(search.toLowerCase()));
  return <section className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">{title}</h2><p className="mt-1 text-sm text-muted-foreground">Одно меню для клиента, оператора и кухни.</p></div><Button onClick={mode==='modifiers'?newGroup:newItem}>+ {mode==='modifiers'?'Создать группу добавок':mode==='combos'?'Создать комбо':'Добавить блюдо'}</Button></div>
    {error && !item && !group && <div role="alert" className="rounded-xl border border-red-300 p-3">{error}<Button variant="link" onClick={()=>void load()}>Повторить</Button></div>}
    {!catalog ? <p role="status">Загружаем меню…</p>:<><div className="flex flex-wrap gap-4"><Input className="max-w-sm" placeholder="Найти по названию" value={search} onChange={e=>setSearch(e.target.value)}/>{checkbox('Показать архив',showArchive,setShowArchive)}</div>
      {mode==='modifiers'?<div className="space-y-3">{catalog.groups.filter(g=>(showArchive || !g.archived_at) && g.name.toLowerCase().includes(search.toLowerCase())).map(g=><article key={g.id} className="rounded-xl border bg-card p-4"><div className="flex justify-between gap-3"><div><h3 className="font-semibold">{g.name}</h3><p className="text-sm text-muted-foreground">{g.archived_at?'В архиве':g.is_active===false?'Выключена':'Активна'} · {g.is_required?'Обязательная':'По желанию'} · {g.min_select}–{g.max_select}</p></div><Button variant="outline" onClick={()=>{setError('');setGroup(structuredClone(g));}}>Изменить</Button></div><ul className="mt-3 flex flex-wrap gap-2 text-sm">{g.options.filter(o=>!o.archived_at).map(o=><li className="rounded-lg bg-muted px-3 py-2" key={o.id}>{o.name} · {menuMoney(o.price)}{o.is_active===false?' · выключен':''}</li>)}</ul></article>)}{!catalog.groups.length && <p className="rounded-xl border p-6">Создайте одну группу, затем подключите её галочками к нужным блюдам.</p>}</div>
      :<div className="grid gap-3 lg:grid-cols-2">{rows.map(p=><article key={p.id} className="rounded-xl border bg-card p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h3 className="font-semibold">{p.name}</h3><p className="mt-1 font-semibold">{menuMoney(p.price)}</p><p className="mt-2 text-sm text-muted-foreground">Добавки: {p.modifiers_enabled!==false && p.modifier_groups?.length?p.modifier_groups.map(g=>g.name).join(', '):'нет'}</p><p className="mt-1 text-sm">{p.archived_at?'В архиве':p.is_active===false?'Выключено':p.available===false?'В стоп-листе':'В меню'}</p>{p.unavailable_reasons?.map(r=><p key={r} className="mt-1 text-sm text-amber-700">{r}</p>)}{p.is_combo&&!p.combo_config&&<p className="mt-1 text-sm text-amber-700">Старое комбо: укажите состав при редактировании.</p>}</div><Button variant="outline" onClick={()=>{setError('');setItem(structuredClone(p));}}>Изменить</Button></div></article>)}{!rows.length && <p className="rounded-xl border p-6">Пока ничего не найдено.</p>}</div>}</>}
    {(item || group) && <Dialog open onOpenChange={open=>{if(!open&&!busy){setItem(null);setGroup(null);setError('');}}}><DialogContent className="max-w-3xl w-[calc(100%-1rem)] max-h-[94dvh] overflow-y-auto"><DialogHeader><DialogTitle>{group?(group.id?'Изменить группу':'Создать группу добавок'):item?.is_combo?(item.id?'Изменить комбо':'Создать комбо'):'Редактировать блюдо'}</DialogTitle><DialogDescription>Сохранение применит изменения ко всем новым заказам. Старые заказы сохранят свой состав и цены.</DialogDescription></DialogHeader>
      {group && <div className="space-y-4"><label className="block">Название группы<Input value={group.name} onChange={e=>setGroup({...group,name:e.target.value})}/></label><div className="grid gap-3 sm:grid-cols-2">{checkbox('Активна',group.is_active!==false,v=>setGroup({...group,is_active:v}))}{checkbox('Обязательная',group.is_required,v=>setGroup({...group,is_required:v,min_select:v?Math.max(1,group.min_select):group.min_select}))}{checkbox('Разрешить несколько',group.type!=='single',v=>setGroup({...group,type:v?'multiple':'single',max_select:v?3:1,min_select:Math.min(group.min_select,1)}))}{group.type!=='single'&&checkbox('Разрешить количество одной добавки',group.type==='quantity',v=>setGroup({...group,type:v?'quantity':'multiple'}))}{numberInput('Минимум выборов',group.min_select,v=>setGroup({...group,min_select:v}))}{numberInput('Максимум выборов',group.max_select,v=>setGroup({...group,max_select:v}),1)}{numberInput('Порядок группы',group.sort_order || 0,v=>setGroup({...group,sort_order:v}))}</div><h3 className="font-semibold">Варианты добавок</h3>{group.options.map((o,i)=><div key={o.id} className="rounded-xl border p-3 space-y-3"><div className="grid gap-3 sm:grid-cols-3"><label className="text-sm">Название варианта<Input value={o.name} onChange={e=>setGroup({...group,options:group.options.map((x,j)=>i===j?{...x,name:e.target.value}:x)})}/></label>{numberInput('Цена, ₸',o.price,v=>setGroup({...group,options:group.options.map((x,j)=>i===j?{...x,price:v}:x)}))}{numberInput('Порядок варианта',o.sort_order || 0,v=>setGroup({...group,options:group.options.map((x,j)=>i===j?{...x,sort_order:v}:x)}))}</div><div className="flex flex-wrap gap-5">{checkbox('Вариант активен',o.is_active!==false,v=>setGroup({...group,options:group.options.map((x,j)=>i===j?{...x,is_active:v}:x)}))}{checkbox('В архиве',!!o.archived_at,v=>setGroup({...group,options:group.options.map((x,j)=>i===j?{...x,archived_at:v?'archived':null}:x)}))}</div></div>)}<Button variant="outline" onClick={()=>setGroup({...group,options:[...group.options,{id:-Date.now(),name:'',price:0,is_active:true,sort_order:group.options.length}]})}>+ Добавить вариант</Button>{checkbox('Архивировать группу',!!group.archived_at,v=>setGroup({...group,archived_at:v?'archived':null}))}</div>}
      {item && <div className="space-y-5"><label className="block">Название<Input value={item.name} onChange={e=>setItem({...item,name:e.target.value})}/></label><label className="block">Описание<textarea className="w-full rounded-lg border bg-background p-3" value={item.description || ''} onChange={e=>setItem({...item,description:e.target.value})}/></label><div className="grid gap-3 sm:grid-cols-2">{numberInput(item.is_combo?'Фиксированная цена комбо, ₸':'Цена, ₸',item.price,v=>setItem({...item,price:v}))}<label className="text-sm">Категория<select className="min-h-10 w-full rounded-lg border bg-background p-2" value={item.category_id || ''} onChange={e=>setItem({...item,category_id:Number(e.target.value) || null})}><option value="">Без категории</option>{catalog?.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{numberInput('Порядок в меню',item.sort_order || 0,v=>setItem({...item,sort_order:v}))}<label className="text-sm">Вес / объём<Input value={item.weight || ''} onChange={e=>setItem({...item,weight:e.target.value})}/></label></div><ImageUpload value={item.image_url || ''} onChange={url=>setItem({...item,image_url:url})} folder="food" compact/>
        {item.is_combo && <div className="space-y-3 border-t pt-4"><h3 className="font-semibold">Состав комбо</h3><p className="text-sm text-muted-foreground">Обычные цены компонентов повторно не прибавляются.</p>{recipe.components.map((p,i)=>partRow(p,i,v=>changeRecipe({...recipe,components:recipe.components.map((x,j)=>i===j?v:x)}),()=>changeRecipe({...recipe,components:recipe.components.filter((_,j)=>j!==i)})))}<Button variant="outline" onClick={()=>changeRecipe({...recipe,components:[...recipe.components,{item_id:0,quantity:1}]})}>+ Добавить блюдо</Button>
          {recipe.groups.map((g,gi)=><div className="space-y-3 rounded-xl border p-4" key={g.id}><label className="block">Название группы выбора<Input value={g.name} onChange={e=>changeRecipe({...recipe,groups:recipe.groups.map((x,j)=>j===gi?{...x,name:e.target.value}:x)})}/></label><div className="grid grid-cols-2 gap-3">{numberInput('Минимум',g.min_select,v=>changeRecipe({...recipe,groups:recipe.groups.map((x,j)=>j===gi?{...x,min_select:v}:x)}))}{numberInput('Максимум',g.max_select,v=>changeRecipe({...recipe,groups:recipe.groups.map((x,j)=>j===gi?{...x,max_select:v}:x)}),1)}</div>{g.options.map((p,i)=>partRow(p,i,v=>changeRecipe({...recipe,groups:recipe.groups.map((x,j)=>j===gi?{...x,options:x.options.map((z,k)=>k===i?v:z)}:x)}),()=>changeRecipe({...recipe,groups:recipe.groups.map((x,j)=>j===gi?{...x,options:x.options.filter((_,k)=>k!==i)}:x)}),true))}<div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>changeRecipe({...recipe,groups:recipe.groups.map((x,j)=>j===gi?{...x,options:[...x.options,{item_id:0,quantity:1,surcharge:0}]}:x)})}>+ Вариант выбора</Button><Button variant="ghost" onClick={()=>changeRecipe({...recipe,groups:recipe.groups.filter((_,j)=>j!==gi)})}>Убрать группу выбора</Button></div></div>)}<Button variant="outline" onClick={()=>changeRecipe({...recipe,groups:[...recipe.groups,{id:crypto.randomUUID(),name:'',min_select:1,max_select:1,options:[]}]})}>+ Группа выбора внутри комбо</Button></div>}
        <div className="border-t pt-4"><h3 className="font-semibold">Добавки</h3>{checkbox('Разрешить добавки',!!item.modifiers_enabled,v=>setItem({...item,modifiers_enabled:v}))}{item.modifiers_enabled && <div className="rounded-xl bg-muted p-3"><p className="text-sm text-muted-foreground">Какие группы показывать клиенту</p>{catalog?.groups.filter(g=>!g.archived_at).map(g=><div key={g.id}>{checkbox(g.name+(g.is_active===false?' (выключена)':''),!!item.modifier_group_ids?.includes(g.id),v=>setItem({...item,modifier_group_ids:v?[...(item.modifier_group_ids || []),g.id]:(item.modifier_group_ids || []).filter(id=>id!==g.id)}))}</div>)}{!catalog?.groups.length && <p>Сначала создайте группу в разделе «Добавки».</p>}</div>}</div><div className="flex flex-wrap gap-5">{checkbox('Включено в меню',item.is_active!==false,v=>setItem({...item,is_active:v}))}{checkbox('Есть в наличии',item.available!==false,v=>setItem({...item,available:v}))}{checkbox('Популярное',!!item.is_popular,v=>setItem({...item,is_popular:v}))}{checkbox('В архиве',!!item.archived_at,v=>setItem({...item,archived_at:v?'archived':null}))}</div></div>}
      {error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="sticky bottom-0 flex flex-wrap gap-3 border-t bg-background py-3">{item&&<Button variant="outline" onClick={showPreview}>Предпросмотр</Button>}<Button disabled={busy || (!!item && (!item.name.trim() || item.price<=0)) || (!!group && (!group.name.trim() || group.options.some(o=>!o.name.trim() || o.price<0)))} onClick={()=>void save()}>{busy?'Сохраняем…':'Сохранить'}</Button></div>
    </DialogContent></Dialog>}
    {preview && <MenuSelectionDialog product={preview} preview onClose={()=>setPreview(null)}/>}
  </section>;
}
