import { useState } from 'react';
import { type Journey, type DirectionKey, type DayKey, type DaySchedule } from '@/lib/transportSchedule';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
export default function TransportJourneyEditor({value,onChange}:{value:Journey;onChange:(v:Journey)=>void}){
 const [direction,setDirection]=useState<DirectionKey>('outbound');const [day,setDay]=useState<DayKey>('weekday');
 const current=value[direction],schedule=current[day];
 const update=(key:keyof DaySchedule,v:string|boolean)=>onChange({...value,[direction]:{...current,[day]:{...schedule,[key]:v}}});
 return <section className="rounded-xl border p-4 space-y-4"><h3 className="font-semibold">Остановки и расписание</h3><div className="flex flex-wrap gap-2">{(['outbound','inbound']as const).map(d=><button type="button" key={d} aria-pressed={d===direction} className={`min-h-11 rounded-lg border px-3 text-sm ${d===direction?'bg-blue-100 text-blue-900':'bg-background'}`} onClick={()=>setDirection(d)}>{d==='outbound'?'Прямое направление':'Обратное направление'}</button>)}</div>
 <label className="grid gap-2 text-sm font-medium">Остановки по порядку<Textarea aria-label="Остановки по порядку" rows={6} value={current.stops.join('\n')} onChange={e=>onChange({...value,[direction]:{...current,stops:e.target.value.split('\n')}})} placeholder="Каждая остановка с новой строки. Первая — место отправления."/></label><p className="text-xs text-slate-500">Укажите фактический порядок остановок. Обратный путь заполните отдельно: он не всегда совпадает с прямым. Пустое направление будет отмечено как незаполненное.</p>
 <div className="flex flex-wrap gap-2">{([['weekday','Пн–Пт'],['saturday','Суббота'],['sunday','Воскресенье']]as const).map(([d,label])=><button type="button" key={d} aria-pressed={d===day} className={`min-h-11 border rounded-lg px-3 text-sm ${d===day?'bg-blue-100 text-blue-900':'bg-background'}`} onClick={()=>setDay(d)}>{label}</button>)}</div>
 <p className="text-sm">Время отправления от: <strong>{current.stops[0]||'первой остановки'}</strong>. Местное время Караганды.</p>
 <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={schedule.not_running} onChange={e=>onChange({...value,[direction]:{...current,[day]:e.target.checked?{times:'',first:'',last:'',interval:'',not_running:true}:{...schedule,not_running:false}}})}/>В этот день рейсов нет</label>
 {!schedule.not_running&&<><label className="grid gap-2 text-sm font-medium">Точные отправления<Textarea aria-label="Точные отправления" value={schedule.times} onChange={e=>update('times',e.target.value)} rows={3} placeholder="06:10, 06:40, 07:10 — только из подтверждённого расписания"/></label><p className="text-xs text-slate-500">Если точных отправлений нет, оставьте поле пустым и заполните первый / последний рейс и интервал. Не рассчитывайте время на промежуточных остановках самостоятельно.</p><div className="grid grid-cols-1 sm:grid-cols-3 gap-3"><label className="grid gap-2 text-sm">Первый рейс<Input type="time" value={schedule.first} onChange={e=>update('first',e.target.value)}/></label><label className="grid gap-2 text-sm">Последний рейс<Input type="time" value={schedule.last} onChange={e=>update('last',e.target.value)}/></label><label className="grid gap-2 text-sm">Интервал<Input maxLength={80} value={schedule.interval} onChange={e=>update('interval',e.target.value)} placeholder="Например: 15–20 мин"/></label></div></>}
 </section>;
}
