import { useLanguage } from '@/contexts/LanguageContext';
import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { client, withRetry } from '@/lib/api';
import { invalidateAllCaches } from '@/lib/cache';
import { httpsLink } from '@/lib/directoryContent';
import { readJourney, newJourney, journeyError, verifiedRoute, type BusRoute, type Journey, type BusNotice } from '@/lib/transportSchedule';
import TransportJourneyEditor from '@/components/TransportJourneyEditor';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
const label='grid gap-2 text-sm font-medium';
export default function AdminTransport(){
  const { t: adminT } = useLanguage();

 const [routes,setRoutes]=useState<BusRoute[]>([]),[notices,setNotices]=useState<BusNotice[]>([]);
 const [loading,setLoading]=useState(true),[loadError,setLoadError]=useState(false),[busy,setBusy]=useState(false);
 const [edit,setEdit]=useState<Partial<BusRoute>|null>(null),[journey,setJourney]=useState<Journey>(newJourney);
 const [message,setMessage]=useState(''),[error,setError]=useState('');const lock=useRef(false),generation=useRef(0);
 const [noticeEdit,setNoticeEdit]=useState<Partial<BusNotice>|null>(null);
 const [legacy,setLegacy]=useState<Array<{route_id:number;stop_name:string;stop_order:number}>>([]);
 async function load(){const version=++generation.current;setLoading(true);setLoadError(false);try{
   const fetchAll=async(entity:'bus_routes'|'bus_stops'|'bus_notifications')=>{const all=[];for(let skip=0;;skip+=200){const r=await withRetry(()=>client.entities[entity].query({sort:'id',skip,limit:200}));const page=r.data?.items||[];all.push(...page);if(page.length<200||all.length>=(r.data?.total??Infinity))break;}return all;};
   const [r,n,s]=await Promise.all([fetchAll('bus_routes'),fetchAll('bus_notifications'),fetchAll('bus_stops')]);if(version===generation.current){setRoutes(r);setNotices(n);setLegacy(s);}
 }catch{if(version===generation.current)setLoadError(true);}finally{if(version===generation.current)setLoading(false);}}
 useEffect(()=>{void load();return()=>{generation.current++;};},[]);
 function open(route?:BusRoute){setError('');setEdit(route?{...route}:{route_number:'',route_name:'',is_active:false,sort_order:routes.length+1});setJourney(route?readJourney(route.journey_json):newJourney());}
 async function save(){if(!edit||lock.current)return;setError('');const clean=structuredClone(journey);for(const d of Object.values(clean))d.stops=d.stops.map(s=>s.trim()).filter(Boolean);const issue=journeyError(clean);if(issue)return setError(issue);
  const data={...edit,route_number:edit.route_number?.trim(),route_name:edit.route_name?.trim(),journey_json:JSON.stringify(clean)};
  if(!data.route_number||!data.route_name)return setError(adminT("admin.ui.1194"));
  if((data.source_url&&!httpsLink(data.source_url))||(data.map_url&&!httpsLink(data.map_url)))return setError(adminT("admin.ui.1195"));
  if(data.is_active&&!verifiedRoute(data as BusRoute))return setError(adminT("admin.ui.1196"));
  lock.current=true;setBusy(true);try{const{id,...body}=data;if(id)await client.entities.bus_routes.update({id:String(id),data:body});else await client.entities.bus_routes.create({data:body});invalidateAllCaches();setEdit(null);setMessage(adminT("admin.ui.1197"));await load();}catch{setError(adminT("admin.ui.1198"));}finally{lock.current=false;setBusy(false);}
 }
 async function saveNotice(){if(!noticeEdit?.message?.trim()||lock.current)return;lock.current=true;setBusy(true);setError('');try{const{id,...body}=noticeEdit;if(id)await client.entities.bus_notifications.update({id:String(id),data:body});else await client.entities.bus_notifications.create({data:{...body,created_at:new Date().toISOString()}});invalidateAllCaches();setNoticeEdit(null);setMessage(adminT("admin.ui.1199"));await load();}catch{setError(adminT("admin.ui.1200"));}finally{lock.current=false;setBusy(false);}}
 return <div className="space-y-5"><div className="rounded-xl border p-4 bg-slate-50 dark:bg-slate-900"><h2 className="text-lg font-bold">{adminT("admin.ui.1201")}</h2><p className="text-sm mt-2">{adminT("admin.ui.1202")}</p><p className="text-sm mt-2">{adminT("admin.ui.1203")}</p><Link className="inline-flex items-center min-h-11 text-blue-700 dark:text-blue-300 underline" to="/transport">{adminT("admin.ui.1204")}</Link></div>
 {message&&<p role="status" className="p-3 rounded-lg bg-slate-100 dark:bg-slate-800">{message}</p>}
 {loading?<p role="status">{adminT("admin.ui.1205")}</p>:loadError?<div role="alert">{adminT("admin.ui.1206")} <Button onClick={()=>void load()}>{adminT("admin.ui.0445")}</Button></div>:<><Button disabled={busy} onClick={()=>open()}>{adminT("admin.ui.1207")}</Button><div className="space-y-3">{routes.map(r=><article key={r.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-4"><div className="min-w-0 flex-1 break-words"><h3 className="font-semibold">№{r.route_number} · {r.route_name}</h3><p className="text-sm text-slate-500">{verifiedRoute(r)?adminT("admin.ui.1208"):r.is_active?adminT("admin.ui.1209"):adminT("admin.ui.0289")}</p></div><Button disabled={busy} variant="outline" aria-label={adminT("admin.extra.1299").replace('{0}', () => String(r.route_number))} onClick={()=>open(r)}>{adminT("admin.ui.0073")}</Button></article>)}</div>
 <section className="border-t pt-5 space-y-3"><div className="flex flex-wrap gap-3 justify-between items-center"><h3 className="font-bold">{adminT("admin.ui.1210")}</h3><Button disabled={busy} variant="outline" onClick={()=>{setError('');setNoticeEdit({message:'',route_id:null,is_active:true});}}>{adminT("admin.ui.1211")}</Button></div><p className="text-sm text-slate-500">{adminT("admin.ui.1212")}</p>{notices.map(n=><article key={n.id} className="rounded-lg border p-3"><p className="text-xs text-slate-500">{n.route_id?adminT("admin.extra.1300").replace('{0}', () => String(routes.find(r=>r.id===n.route_id)?.route_number||n.route_id)):adminT("admin.ui.1213")} · {n.is_active?adminT("admin.ui.1214"):adminT("admin.ui.0043")}</p><p className="text-sm my-2 break-words">{n.message}</p><Button variant="outline" disabled={busy} onClick={()=>{setError('');setNoticeEdit({...n});}}>{adminT("admin.ui.1215")}</Button></article>)}</section></>}
 <Dialog open={!!edit} onOpenChange={v=>{if(!v&&!lock.current)setEdit(null);}}><DialogContent className="max-w-3xl max-h-[90dvh] overflow-y-auto"><DialogHeader><DialogTitle>{edit?.id?adminT("admin.ui.1216"):adminT("admin.ui.1217")}</DialogTitle><DialogDescription>{adminT("admin.ui.1218")}</DialogDescription></DialogHeader>{edit&&<form onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy} className="space-y-4"><div className="grid grid-cols-1 sm:grid-cols-3 gap-3"><label className={label}>{adminT("admin.ui.1219")}<Input maxLength={20} value={edit.route_number||''} onChange={e=>setEdit({...edit,route_number:e.target.value})}/></label><label className={`${label} sm:col-span-2`}>{adminT("admin.ui.1220")}<Input maxLength={200} value={edit.route_name||''} onChange={e=>setEdit({...edit,route_name:e.target.value})}/></label></div>
 <TransportJourneyEditor value={journey} onChange={setJourney}/>
 {!edit.journey_json&&legacy.some(s=>s.route_id===edit.id)&&<details className="rounded-lg border p-3 text-sm"><summary className="cursor-pointer min-h-11">{adminT("admin.ui.1221")}</summary><p className="my-2 text-amber-700">{adminT("admin.ui.1222")}</p><ol className="list-decimal pl-5">{legacy.filter(s=>s.route_id===edit.id).sort((a,b)=>a.stop_order-b.stop_order).map((s,i)=><li key={i}>{s.stop_name}</li>)}</ol></details>}
 <label className={label}>{adminT("admin.ui.1223")}<Textarea maxLength={2000} value={edit.description||''} onChange={e=>setEdit({...edit,description:e.target.value})}/></label>
 <label className={label}>{adminT("admin.ui.1224")}<Input value={edit.source_url||''} onChange={e=>setEdit({...edit,source_url:e.target.value})} placeholder={adminT("admin.ui.1225")}/></label>
 <label className={label}>{adminT("admin.ui.1226")}<Input type="date" max={new Date().toLocaleDateString('sv-SE')} value={edit.verified_at||''} onChange={e=>setEdit({...edit,verified_at:e.target.value})}/></label>
 <label className={label}>{adminT("admin.ui.1227")}<Input value={edit.map_url||''} onChange={e=>setEdit({...edit,map_url:e.target.value})} placeholder={adminT("admin.ui.1228")}/></label>
 <label className={label}>{adminT("admin.ui.1229")}<Input type="number" min={0} value={edit.sort_order??0} onChange={e=>setEdit({...edit,sort_order:Number(e.target.value)})}/></label>
 <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={edit.is_active===true} onChange={e=>setEdit({...edit,is_active:e.target.checked})}/>{adminT("admin.ui.1230")}</label>{error&&<p role="alert" className="text-red-700 rounded-lg bg-red-50 p-3 text-sm">{error}</p>}<div className="flex flex-wrap gap-2"><Button type="submit">{busy?adminT("admin.ui.0476"):edit.is_active?adminT("admin.ui.0477"):adminT("admin.ui.0316")}</Button><Button type="button" variant="outline" onClick={()=>setEdit(null)}>{adminT("admin.ui.0095")}</Button></div></fieldset></form>}</DialogContent></Dialog>
 <Dialog open={!!noticeEdit} onOpenChange={v=>{if(!v&&!lock.current)setNoticeEdit(null);}}><DialogContent><DialogHeader><DialogTitle>{adminT("admin.ui.1231")}</DialogTitle><DialogDescription>{adminT("admin.ui.1232")}</DialogDescription></DialogHeader>{noticeEdit&&<form onSubmit={e=>{e.preventDefault();void saveNotice();}}><fieldset disabled={busy} className="space-y-4"><label className={label}>{adminT("admin.ui.1175")}<select className="h-11 rounded border bg-background px-3" value={noticeEdit.route_id??''} onChange={e=>setNoticeEdit({...noticeEdit,route_id:e.target.value?Number(e.target.value):null})}><option value="">{adminT("admin.ui.1213")}</option>{routes.map(r=><option key={r.id} value={r.id}>№{r.route_number}</option>)}</select></label><label className={label}>{adminT("admin.ui.1233")}<Textarea required maxLength={2000} value={noticeEdit.message||''} onChange={e=>setNoticeEdit({...noticeEdit,message:e.target.value})}/></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={noticeEdit.is_active===true} onChange={e=>setNoticeEdit({...noticeEdit,is_active:e.target.checked})}/>{adminT("admin.ui.1234")}</label>{error&&<p role="alert">{error}</p>}<Button type="submit">{adminT("admin.ui.1235")}</Button></fieldset></form>}</DialogContent></Dialog>
 </div>;
}
