import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { client, withRetry } from '@/lib/api';
import { invalidateAllCaches } from '@/lib/cache';
import { httpsLink } from '@/lib/directoryContent';
import { readJourney, newJourney, journeyError, verifiedRoute, type BusRoute, type Journey, type BusNotice } from '@/lib/transportSchedule';
import TransportJourneyEditor from '@/components/TransportJourneyEditor';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
const label='grid gap-2 text-sm font-medium';
export default function AdminTransport(){
 const [routes,setRoutes]=useState<BusRoute[]>([]),[notices,setNotices]=useState<BusNotice[]>([]);
 const [loading,setLoading]=useState(true),[loadError,setLoadError]=useState(false),[busy,setBusy]=useState(false);
 const [edit,setEdit]=useState<Partial<BusRoute>|null>(null),[journey,setJourney]=useState<Journey>(newJourney);
 const [message,setMessage]=useState(''),[error,setError]=useState('');const lock=useRef(false),generation=useRef(0);
 const [noticeEdit,setNoticeEdit]=useState<Partial<BusNotice>|null>(null);
 const [legacy,setLegacy]=useState<Array<{route_id:number;stop_name:string;stop_order:number}>>([]);
 async function load(){const version=++generation.current;setLoading(true);setLoadError(false);try{
   const fetchAll=async(entity:'bus_routes'|'bus_stops'|'bus_notifications')=>{const all=[];for(let skip=0;;skip+=200){const r=await withRetry(()=>client.entities[entity].query({sort:'id',skip,limit:200}));const page=r.data?.items||[];all.push(...page);if(page.length<200||all.length>=(r.data?.total??Infinity))break;}return all;};
   const [r,n,s]=await Promise.all([fetchAll('bus_routes'),fetchAll('bus_notifications'),fetchAll('bus_stops')]);if(version===generation.current){setRoutes(r);setNotices(n);setLegacy(s);}
 }catch{if(version===generation.current)setLoadError(true);}finally{if(version===generation.current)setLoading(false);}}
 useEffect(()=>{void load();return()=>{generation.current++;};},[]);
 function open(route?:BusRoute){setError('');setEdit(route?{...route}:{route_number:'',route_name:'',is_active:false,sort_order:routes.length+1});setJourney(route?readJourney(route.journey_json):newJourney());}
 async function save(){if(!edit||lock.current)return;setError('');const clean=structuredClone(journey);for(const d of Object.values(clean))d.stops=d.stops.map(s=>s.trim()).filter(Boolean);const issue=journeyError(clean);if(issue)return setError(issue);
  const data={...edit,route_number:edit.route_number?.trim(),route_name:edit.route_name?.trim(),journey_json:JSON.stringify(clean)};
  if(!data.route_number||!data.route_name)return setError('Укажите номер и название маршрута.');
  if((data.source_url&&!httpsLink(data.source_url))||(data.map_url&&!httpsLink(data.map_url)))return setError('Ссылка должна начинаться с https://.');
  if(data.is_active&&!verifiedRoute(data as BusRoute))return setError('Для публикации нужны источник, дата проверки и минимум две остановки в одном направлении.');
  lock.current=true;setBusy(true);try{const{id,...body}=data;if(id)await client.entities.bus_routes.update({id:String(id),data:body});else await client.entities.bus_routes.create({data:body});invalidateAllCaches();setEdit(null);setMessage('Маршрут сохранён.');await load();}catch{setError('Не удалось подтвердить сохранение. Перед повторным созданием обновите список, чтобы исключить дубликат.');}finally{lock.current=false;setBusy(false);}
 }
 async function saveNotice(){if(!noticeEdit?.message?.trim()||lock.current)return;lock.current=true;setBusy(true);setError('');try{const{id,...body}=noticeEdit;if(id)await client.entities.bus_notifications.update({id:String(id),data:body});else await client.entities.bus_notifications.create({data:{...body,created_at:new Date().toISOString()}});invalidateAllCaches();setNoticeEdit(null);setMessage('Сообщение сохранено.');await load();}catch{setError('Не удалось сохранить сообщение.');}finally{lock.current=false;setBusy(false);}}
 return <div className="space-y-5"><div className="rounded-xl border p-4 bg-slate-50 dark:bg-slate-900"><h2 className="text-lg font-bold">Автобусы: маршруты и расписание</h2><p className="text-sm mt-2">Для каждого автобуса заполните остановки отдельно в обе стороны. Затем укажите отправления от первой остановки по будням, субботам и воскресеньям. Пустое время означает «расписание уточняется», а не отсутствие рейсов.</p><p className="text-sm mt-2">Старые записи сохранены для сверки. На сайте показываются только маршруты с источником и датой проверки. Сохраните черновик, если данные не готовы.</p><Link className="inline-flex items-center min-h-11 text-blue-700 dark:text-blue-300 underline" to="/transport">Открыть страницу автобусов ↗</Link></div>
 {message&&<p role="status" className="p-3 rounded-lg bg-slate-100 dark:bg-slate-800">{message}</p>}
 {loading?<p role="status">Загрузка…</p>:loadError?<div role="alert">Не удалось загрузить данные. <Button onClick={()=>void load()}>Повторить</Button></div>:<><Button disabled={busy} onClick={()=>open()}>Добавить автобус</Button><div className="space-y-3">{routes.map(r=><article key={r.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-4"><div className="min-w-0 flex-1 break-words"><h3 className="font-semibold">№{r.route_number} · {r.route_name}</h3><p className="text-sm text-slate-500">{verifiedRoute(r)?'Опубликован':r.is_active?'Требует проверки':'Черновик'}</p></div><Button disabled={busy} variant="outline" aria-label={`Редактировать автобус ${r.route_number}`} onClick={()=>open(r)}>Редактировать</Button></article>)}</div>
 <section className="border-t pt-5 space-y-3"><div className="flex flex-wrap gap-3 justify-between items-center"><h3 className="font-bold">Изменения и объявления</h3><Button disabled={busy} variant="outline" onClick={()=>{setError('');setNoticeEdit({message:'',route_id:null,is_active:true});}}>Добавить сообщение</Button></div><p className="text-sm text-slate-500">Сообщение для всех маршрутов показывается один раз. Когда изменение перестало действовать, снимите отметку «Показывать».</p>{notices.map(n=><article key={n.id} className="rounded-lg border p-3"><p className="text-xs text-slate-500">{n.route_id?`Автобус ${routes.find(r=>r.id===n.route_id)?.route_number||n.route_id}`:'Все маршруты'} · {n.is_active?'Показывается':'Скрыто'}</p><p className="text-sm my-2 break-words">{n.message}</p><Button variant="outline" disabled={busy} onClick={()=>{setError('');setNoticeEdit({...n});}}>Изменить сообщение</Button></article>)}</section></>}
 <Dialog open={!!edit} onOpenChange={v=>{if(!v&&!lock.current)setEdit(null);}}><DialogContent className="max-w-3xl max-h-[90dvh] overflow-y-auto"><DialogHeader><DialogTitle>{edit?.id?'Редактировать автобус':'Новый автобус'}</DialogTitle><DialogDescription>Расписание и остановки сохраняются вместе. Обратное направление не формируется автоматически.</DialogDescription></DialogHeader>{edit&&<form onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy} className="space-y-4"><div className="grid grid-cols-1 sm:grid-cols-3 gap-3"><label className={label}>Номер автобуса *<Input maxLength={20} value={edit.route_number||''} onChange={e=>setEdit({...edit,route_number:e.target.value})}/></label><label className={`${label} sm:col-span-2`}>Название маршрута *<Input maxLength={200} value={edit.route_name||''} onChange={e=>setEdit({...edit,route_name:e.target.value})}/></label></div>
 <TransportJourneyEditor value={journey} onChange={setJourney}/>
 {!edit.journey_json&&legacy.some(s=>s.route_id===edit.id)&&<details className="rounded-lg border p-3 text-sm"><summary className="cursor-pointer min-h-11">Старые остановки — только для сверки</summary><p className="my-2 text-amber-700">Этот список не подтверждён. Не переносите его без проверки.</p><ol className="list-decimal pl-5">{legacy.filter(s=>s.route_id===edit.id).sort((a,b)=>a.stop_order-b.stop_order).map((s,i)=><li key={i}>{s.stop_name}</li>)}</ol></details>}
 <label className={label}>Примечание: праздники, временные изменения<Textarea maxLength={2000} value={edit.description||''} onChange={e=>setEdit({...edit,description:e.target.value})}/></label>
 <label className={label}>Источник маршрута и расписания<Input value={edit.source_url||''} onChange={e=>setEdit({...edit,source_url:e.target.value})} placeholder="https://… — страница перевозчика или официальный документ"/></label>
 <label className={label}>Дата проверки<Input type="date" max={new Date().toLocaleDateString('sv-SE')} value={edit.verified_at||''} onChange={e=>setEdit({...edit,verified_at:e.target.value})}/></label>
 <label className={label}>Ссылка на карту маршрута<Input value={edit.map_url||''} onChange={e=>setEdit({...edit,map_url:e.target.value})} placeholder="https://… (необязательно)"/></label>
 <label className={label}>Порядок в списке<Input type="number" min={0} value={edit.sort_order??0} onChange={e=>setEdit({...edit,sort_order:Number(e.target.value)})}/></label>
 <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={edit.is_active===true} onChange={e=>setEdit({...edit,is_active:e.target.checked})}/>Опубликовать после проверки</label>{error&&<p role="alert" className="text-red-700 rounded-lg bg-red-50 p-3 text-sm">{error}</p>}<div className="flex flex-wrap gap-2"><Button type="submit">{busy?'Сохранение…':edit.is_active?'Сохранить и опубликовать':'Сохранить черновик'}</Button><Button type="button" variant="outline" onClick={()=>setEdit(null)}>Отмена</Button></div></fieldset></form>}</DialogContent></Dialog>
 <Dialog open={!!noticeEdit} onOpenChange={v=>{if(!v&&!lock.current)setNoticeEdit(null);}}><DialogContent><DialogHeader><DialogTitle>Сообщение пассажирам</DialogTitle><DialogDescription>Укажите только действующее изменение маршрута или расписания.</DialogDescription></DialogHeader>{noticeEdit&&<form onSubmit={e=>{e.preventDefault();void saveNotice();}}><fieldset disabled={busy} className="space-y-4"><label className={label}>Маршрут<select className="h-11 rounded border bg-background px-3" value={noticeEdit.route_id??''} onChange={e=>setNoticeEdit({...noticeEdit,route_id:e.target.value?Number(e.target.value):null})}><option value="">Все маршруты</option>{routes.map(r=><option key={r.id} value={r.id}>№{r.route_number}</option>)}</select></label><label className={label}>Сообщение<Textarea required maxLength={2000} value={noticeEdit.message||''} onChange={e=>setNoticeEdit({...noticeEdit,message:e.target.value})}/></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={noticeEdit.is_active===true} onChange={e=>setNoticeEdit({...noticeEdit,is_active:e.target.checked})}/>Показывать</label>{error&&<p role="alert">{error}</p>}<Button type="submit">Сохранить сообщение</Button></fieldset></form>}</DialogContent></Dialog>
 </div>;
}
