import {useCallback,useEffect,useRef,useState} from 'react';
import {useLanguage} from '@/contexts/LanguageContext';
import {foodOperations} from '@/lib/foodOperations';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {printDocument,escapePrint} from '@/lib/receiptPrint';
import {toast} from 'sonner';

type Basis='kitchen'|'bar'|'all';
type Rates={daily_base:number;percent:number;basis:Basis};
type Employee=Rates&{id:number;name:string;position:string;active:boolean};
type Row=Rates&{employee_id:number;name:string;position:string;sales:number;commission:number;total:number;paid:number;remaining:number};
type Report={day:string;version:number;fingerprint:string;closed:boolean;rows:Row[];sales:Record<string,number>;total:number;pending_orders:number;unassigned:number;new_sales_after_close:number;payments:{id:string;employee_id:number;amount:number;note:string;created_at:string;voided?:boolean}[]};
const api=<T,>(path:string,method='GET',body?:unknown)=>foodOperations<T>(path,method,body,'payroll');
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Almaty',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());

function RateFields({rates,setRates}:{rates:Rates;setRates:(r:Rates)=>void}) {
 const {t}=useLanguage();
 return <div className="grid sm:grid-cols-3 gap-3"><label className="block text-sm">{t('payroll.base')}<Input type="number" min={0} step="0.01" value={rates.daily_base} onChange={e=>setRates({...rates,daily_base:Number(e.target.value)})}/></label><label className="block text-sm">{t('payroll.percent')}<Input type="number" min={0} max={100} step="0.01" value={rates.percent} onChange={e=>setRates({...rates,percent:Number(e.target.value)})}/></label><label className="block text-sm">{t('payroll.basis')}<select className="w-full border rounded-lg p-2 bg-background" value={rates.basis} onChange={e=>setRates({...rates,basis:e.target.value as Basis})}>{(['kitchen','bar','all'] as const).map(x=><option key={x} value={x}>{t(`payroll.${x}`)}</option>)}</select></label></div>;
}

function Payout({row,busy,submit}:{row:Row;busy:boolean;submit:(amount:number,note:string,id:string)=>Promise<void>}) {
 const {t}=useLanguage();const [amount,setAmount]=useState(row.remaining),[note,setNote]=useState('');
 const id=useRef(crypto.randomUUID());
 return <div className="flex flex-wrap items-end gap-2"><label className="text-sm">{t('payroll.payAmount')}<Input type="number" className="w-36" min={0.01} max={row.remaining} step="0.01" value={amount} onChange={e=>{setAmount(Number(e.target.value));id.current=crypto.randomUUID();}} /></label><label className="text-sm flex-1">{t('payroll.note')}<Input maxLength={500} value={note} onChange={e=>setNote(e.target.value)}/></label><Button disabled={busy||amount<=0||amount>row.remaining} onClick={()=>void submit(amount,note,id.current)}>{t('payroll.recordPayment')}</Button></div>;
}

export default function DamAlemPayroll() {
 const {t}=useLanguage();const [day,setDay]=useState(today),[employees,setEmployees]=useState<Employee[]>([]),[data,setData]=useState<Report|null>(null);
 const [products,setProducts]=useState<{id:number;name:string;department:Basis|null}[]>([]),[filter,setFilter]=useState('');
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState<'day'|'employees'|'menu'>('day');
 const [editId,setEditId]=useState<number|null>(null),[name,setName]=useState(''),[position,setPosition]=useState(''),[rates,setRates]=useState<Rates>({daily_base:0,percent:0,basis:'kitchen'});
 const [workEdit,setWorkEdit]=useState<Row|null>(null);const lock=useRef(false);const generation=useRef(0);
 const load=useCallback(async()=>{const request=++generation.current;try{const [staff,report,catalog]=await Promise.all([api<Employee[]>('/employees'),api<Report>('/days/'+day),api<typeof products>('/departments')]);if(request!==generation.current)return;setEmployees(staff);setData(report);setProducts(catalog);setError('');}catch(e){if(request===generation.current)setError((e as Error).message);}},[day]);
 useEffect(()=>{setData(null);void load();},[load]);
 async function action(work:()=>Promise<unknown>) {if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await work();await load();toast.success(t('workflow.saved'));}catch(e){setError((e as Error).message);}finally{setBusy(false);lock.current=false;}}
 async function printRows(rows:Row[]) {
   try{await printDocument(`${t('payroll.title')} ${day}`,`<h1>DAM ALEM 2.0</h1><h2>${escapePrint(t('payroll.title'))} · ${escapePrint(day)}</h2>${rows.map(r=>`<h2>${escapePrint(r.name)}</h2><p>${escapePrint(r.position)}</p><p>${escapePrint(t('payroll.base'))}: ${r.daily_base} ₸</p><p>${escapePrint(t(`payroll.${r.basis}`))}: ${r.sales} ₸ × ${r.percent}% = ${r.commission} ₸</p><p>${escapePrint(t('payroll.accrued'))}: ${r.total} ₸</p><p>${escapePrint(t('payroll.paid'))}: ${r.paid} ₸</p><p>${escapePrint(t('payroll.remaining'))}: ${r.remaining} ₸</p><hr>`).join('')}<small>${escapePrint(t(data?.closed?'payroll.closed':'payroll.draft'))}</small>`);}catch(e){toast.error((e as Error).message);}
 }
 return <section className="space-y-4 min-w-0"><div className="flex flex-wrap gap-3 justify-between"><div><h3 className="text-xl font-bold">{t('payroll.title')}</h3><p className="text-sm text-muted-foreground">{t('payroll.subtitle')}</p></div><Button variant="outline" disabled={busy} onClick={()=>void load()}>{t('payroll.refresh')}</Button></div>
   <div className="flex flex-wrap gap-2">{(['day','employees','menu'] as const).map(x=><Button key={x} variant={tab===x?'default':'outline'} onClick={()=>setTab(x)}>{t(`payroll.tab.${x}`)}</Button>)}</div>
   {error&&<p role="alert" className="rounded-xl bg-red-50 text-red-800 p-3">{error}</p>}
   {tab==='employees'&&<><p className="text-sm text-muted-foreground">{t('payroll.rateHint')}</p><fieldset disabled={busy} className="rounded-xl border p-4 space-y-3"><label className="block">{t('payroll.name')}<Input value={name} maxLength={150} onChange={e=>setName(e.target.value)}/></label><label className="block">{t('payroll.position')}<Input value={position} maxLength={150} onChange={e=>setPosition(e.target.value)}/></label><RateFields rates={rates} setRates={setRates}/><Button disabled={!name.trim()||!position.trim()} onClick={()=>void action(async()=>{await api(editId?'/employees/'+editId:'/employees',editId?'PUT':'POST',{name,position,...rates,active:true});setEditId(null);setName('');setPosition('');})}>{t(editId?'payroll.save':'payroll.add')}</Button></fieldset>{employees.map(e=><div key={e.id} className="rounded-xl border p-4 flex flex-wrap gap-3 justify-between"><div><strong>{e.name}</strong><p>{e.position}: {e.daily_base} ₸ + {e.percent}% · {t(`payroll.${e.basis}`)}</p></div><Button variant="outline" onClick={()=>{setEditId(e.id);setName(e.name);setPosition(e.position);setRates({daily_base:e.daily_base,percent:e.percent,basis:e.basis});}}>{t('payroll.edit')}</Button><Button disabled={busy} variant="outline" onClick={()=>void action(()=>api('/employees/'+e.id,'PUT',{...e,active:!e.active}))}>{t(e.active?'payroll.deactivate':'payroll.activate')}</Button></div>)}</>}
   {tab==='menu'&&<><p className="text-sm text-muted-foreground">{t('payroll.departmentHint')}</p><Input aria-label={t('workflow.search')} placeholder={t('workflow.search')} value={filter} onChange={e=>setFilter(e.target.value)}/>{products.filter(x=>x.name.toLowerCase().includes(filter.toLowerCase())).map(x=><label key={x.id} className="rounded-xl border p-3 flex flex-wrap justify-between gap-3 items-center"><span className="break-words">{x.name}</span><select disabled={busy} className="border rounded-lg p-2 bg-background" value={x.department||''} onChange={e=>void action(()=>api('/departments/'+x.id,'PUT',{department:e.target.value}))}><option value="" disabled>{t('payroll.unassigned')}</option><option value="kitchen">{t('payroll.kitchen')}</option><option value="bar">{t('payroll.bar')}</option></select></label>)}</>}
   {tab==='day'&&<><label className="block max-w-xs">{t('payroll.day')}<Input type="date" value={day} disabled={busy} onChange={e=>{if(e.target.value)setDay(e.target.value);setWorkEdit(null);}}/></label><p className="text-sm text-muted-foreground">{t('payroll.formula')}</p>{!data&&!error&&<p>{t('workflow.loading')}</p>}{data&&<>
     <div className="grid sm:grid-cols-3 gap-3">{(['kitchen','bar','unassigned'] as const).map(key=><div key={key} className="border rounded-xl p-3"><p>{t(`payroll.${key}`)}</p><strong>{data.sales[key]} ₸</strong></div>)}</div>
     {data.pending_orders>0&&!data.closed&&<p className="rounded-xl bg-amber-50 text-amber-900 p-3">{t('payroll.pending')}: {data.pending_orders}</p>}
     {data.new_sales_after_close>0&&<p role="alert" className="rounded-xl bg-amber-50 text-amber-900 p-3">{t('payroll.lateSales')}: {data.new_sales_after_close}</p>}
     {!data.closed&&<div className="flex flex-wrap gap-2">{employees.filter(e=>e.active&&!data.rows.some(r=>r.employee_id===e.id)).map(e=><Button key={e.id} variant="outline" disabled={busy} onClick={()=>void action(()=>api(`/days/${day}/work/${e.id}`,'PUT',{...e,expected_version:data.version,worked:true}))}>{t('payroll.worked')}: {e.name}</Button>)}</div>}
     {!employees.length&&<Button onClick={()=>setTab('employees')}>{t('payroll.add')}</Button>}
     {data.rows.map(row=><article key={row.employee_id} className="rounded-2xl border p-4 space-y-3 bg-card"><div className="flex flex-wrap justify-between gap-3"><div><h4 className="font-bold">{row.name}</h4><p className="text-sm text-muted-foreground">{row.position}</p></div><Button variant="outline" onClick={()=>void printRows([row])}>{t('payroll.print')}</Button></div><p>{row.daily_base} ₸ + {row.percent}% × {row.sales} ₸ ({t(`payroll.${row.basis}`)})</p><div className="flex flex-wrap gap-4"><strong>{t('payroll.accrued')}: {row.total} ₸</strong><span>{t('payroll.paid')}: {row.paid} ₸</span><strong>{t('payroll.remaining')}: {row.remaining} ₸</strong></div>
       {!data.closed&&<div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>setWorkEdit({...row})}>{t('payroll.dayRates')}</Button><Button variant="outline" disabled={busy} onClick={()=>void action(()=>api(`/days/${day}/work/${row.employee_id}`,'PUT',{...row,worked:false,expected_version:data.version}))}>{t('payroll.removeWork')}</Button></div>}
       {workEdit?.employee_id===row.employee_id&&!data.closed&&<fieldset disabled={busy} className="border-t pt-3 space-y-3"><RateFields rates={workEdit} setRates={r=>setWorkEdit({...workEdit,...r})}/><Button onClick={()=>void action(async()=>{await api(`/days/${day}/work/${row.employee_id}`,'PUT',{...workEdit,worked:true,expected_version:data.version});setWorkEdit(null);})}>{t('payroll.save')}</Button></fieldset>}
       {data.closed&&row.remaining>0&&<Payout key={`${row.employee_id}:${row.paid}`} row={row} busy={busy} submit={(amount,note,id)=>action(()=>api(`/days/${day}/payments`,'POST',{id,employee_id:row.employee_id,amount,note,expected_version:data.version}))}/>}
     </article>)}
     <div className="rounded-xl bg-muted p-4 space-y-3"><p className="font-bold">{t('payroll.accrued')}: {data.total} ₸ · {t(data.closed?'payroll.closed':'payroll.draft')}</p><p className="text-sm">{t('payroll.closeHint')}</p><div className="flex flex-wrap gap-2"><Button disabled={busy||!data.rows.length} onClick={()=>void action(()=>api(`/days/${day}/${data.closed?'reopen':'close'}`,'POST',{expected_version:data.version,fingerprint:data.fingerprint}))}>{t(data.closed?'payroll.reopen':'payroll.close')}</Button><Button variant="outline" disabled={!data.rows.length} onClick={()=>void printRows(data.rows)}>{t('payroll.print')}</Button></div></div>
     {!!data.payments.length&&<section className="space-y-2"><h4 className="font-bold">{t('payroll.payments')}</h4>{data.payments.map(p=><p key={p.id} className="border-t py-2 text-sm">{data.rows.find(r=>r.employee_id===p.employee_id)?.name}: {p.amount} ₸ {p.voided&&`· ${t('payroll.voided')}`} · {new Date(p.created_at).toLocaleString()} · {p.note}</p>)}</section>}
   </>}</>}
 </section>;
}
