import { useEffect, useRef, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { Bus, Search, ArrowRight, ArrowLeftRight, Clock } from 'lucide-react';
import Layout from '@/components/Layout';
import { useLanguage } from '@/contexts/LanguageContext';
import { client, withRetry } from '@/lib/api';
import { httpsLink } from '@/lib/directoryContent';
import { cityDay, departureTimes, readJourney, verifiedRoute, routeMatches, officialTransportUrl, type BusRoute, type BusNotice, type DayKey, type DirectionKey } from '@/lib/transportSchedule';
import '@/styles/transport.css';

export default function Transport() {
  const { lang } = useLanguage(); const kz = lang === 'kz'; const say = (ru: string, kk: string) => kz ? kk : ru;
  const [params,setParams] = useSearchParams(); const query = params.get('q') || '';
  const [routes,setRoutes] = useState<BusRoute[]>([]); const [notices,setNotices] = useState<BusNotice[]>([]);
  const [loading,setLoading] = useState(true); const [error,setError] = useState(false); const [noticeError,setNoticeError] = useState(false); const generation=useRef(0);
  async function load() {
    const version=++generation.current; setLoading(true);setError(false);setNoticeError(false);
    const results=await Promise.allSettled([
      (async()=>{const all:BusRoute[]=[];for(let skip=0;;skip+=200){const r=await withRetry(()=>client.entities.bus_routes.query({sort:'id',skip,limit:200}));const page=r.data?.items||[];all.push(...page);if(page.length<200||all.length>=(r.data?.total??Infinity))break;}return all;})(),
      withRetry(()=>client.entities.bus_notifications.query({query:{is_active:true},sort:'-created_at',limit:200})),
    ]);
    if(version!==generation.current)return;
    if(results[0].status==='fulfilled')setRoutes(results[0].value.filter(verifiedRoute).sort((a,b)=>(a.sort_order??999)-(b.sort_order??999)||a.route_number.localeCompare(b.route_number,'ru',{numeric:true})));else setError(true);
    if(results[1].status==='fulfilled')setNotices((results[1].value.data?.items||[]).filter((n:BusNotice)=>n.is_active));else{setNotices([]);setNoticeError(true);}setLoading(false);
  }
  useEffect(()=>{void load();return()=>{generation.current++;};},[]);
  const shown=routes.filter(r=>routeMatches(r,query)); const selected=shown.find(r=>String(r.id)===params.get('route'));
  const detailRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{if(selected?.id&&window.innerWidth<=800)detailRef.current?.scrollIntoView({block:'start',behavior:'auto'});},[selected?.id]);
  function change(key:string,value:string){const next=new URLSearchParams(params);if(value)next.set(key,value);else next.delete(key);if(key==='route'){next.delete('direction');next.delete('stop');}if(key==='direction')next.delete('stop');setParams(next,{replace:key==='q'});}
  return <Layout><div className="transport-page"><header className="transport-hero"><div className="transport-width"><Link to="/directory">← {say('Справочник','Анықтамалық')}</Link><h1><Bus aria-hidden="true" />{say('Автобусы Сортировки','Сортировка автобустары')}</h1><p>{say('Найдите автобус. Выберите направление. Посмотрите остановки и расписание.','Автобусты табыңыз. Бағытты таңдаңыз. Аялдамалар мен кестені қараңыз.')}</p></div></header>
    <div className="transport-width transport-body">
      {notices.filter(n=>!n.route_id).map(n=><p key={n.id} className="transport-notice">{n.message}</p>)}
      <label className="transport-search"><Search size={20}/><input aria-label={say('Номер автобуса или остановка','Автобус нөмірі немесе аялдама')} placeholder={say('Номер автобуса или остановка','Автобус нөмірі немесе аялдама')} value={query} onChange={e=>change('q',e.target.value)}/>{query&&<button onClick={()=>change('q','')}>{say('Очистить','Тазалау')}</button>}</label>
      {loading?<p role="status" className="transport-empty">{say('Загружаем маршруты…','Бағыттар жүктелуде…')}</p>:error?<div role="alert" className="transport-empty"><h2>{say('Не удалось загрузить маршруты','Бағыттарды жүктеу мүмкін болмады')}</h2><button onClick={()=>void load()}>{say('Повторить','Қайталау')}</button></div>:!shown.length?<div className="transport-empty"><Bus size={32}/><h2>{routes.length?say('Автобус или остановка не найдены','Автобус немесе аялдама табылмады'):say('Расписания проходят проверку','Кестелер тексерілуде')}</h2><p>{routes.length?say('Попробуйте другой номер или название остановки.','Басқа нөмірді немесе аялдама атауын енгізіңіз.'):say('Готовим актуальные остановки и время отправления. Пока информацию можно уточнить в ONAY! Караганда.','Бағыттар аялдамалар мен кестелер дереккөзбен тексерілген соң жарияланады.')}</p>{query&&<button onClick={()=>change('q','')}>{say('Сбросить поиск','Іздеуді тазалау')}</button>}</div>:<div className="transport-columns"><nav aria-label={say('Автобусные маршруты','Автобус бағыттары')} className="transport-route-list"><p>{say('Выберите автобус','Автобусты таңдаңыз')} · {shown.length}</p>{shown.map(r=><button key={r.id} aria-pressed={selected?.id===r.id} onClick={()=>change('route',String(r.id))}><strong className="transport-number">{r.route_number}</strong><span>{r.route_name}</span><ArrowRight size={18}/></button>)}</nav><div ref={detailRef} className="transport-detail">{selected?<RouteDetails key={selected.id} route={selected} params={params} change={change} notices={notices.filter(n=>n.route_id===selected.id)} kz={kz}/>:<div className="transport-empty"><Bus size={36}/><h2>{say('Какой автобус вам нужен?','Сізге қай автобус керек?')}</h2><p>{say('Выберите номер — здесь появятся оба направления, остановки и время отправления.','Нөмірді таңдаңыз — бағыттар, аялдамалар және жөнелту уақыты көрсетіледі.')}</p></div>}</div></div>}
      {noticeError&&<p className="transport-note">{say('Сообщения об изменениях сейчас недоступны. Уточните информацию у перевозчика.','Өзгерістер туралы хабарламалар қазір қолжетімсіз. Ақпаратты тасымалдаушыдан нақтылаңыз.')}</p>}
      <aside className="transport-official"><div><h2>{say('Информация перевозчиков','Тасымалдаушылар ақпараты')}</h2><p>{say('На этой странице — справочное расписание, а не отслеживание автобусов. Прибытие зависит от дорожной ситуации. В праздники график может отличаться.','Бұл бетте автобустардың қозғалысын бақылау емес, анықтамалық кесте берілген. Келу уақыты жол жағдайына байланысты. Мереке күндері кесте өзгеруі мүмкін.')}</p></div><a href={officialTransportUrl} target="_blank" rel="noopener noreferrer">ONAY! {say('Караганда','Қарағанды')} ↗</a></aside>
    </div></div></Layout>;
}
function RouteDetails({route,params,change,notices,kz}:{route:BusRoute;params:URLSearchParams;change:(k:string,v:string)=>void;notices:BusNotice[];kz:boolean}){
  const say=(ru:string,kk:string)=>kz?kk:ru;const journey=readJourney(route.journey_json);
  const direction:DirectionKey=params.get('direction')==='inbound'?'inbound':params.get('direction')==='outbound'?'outbound':journey.outbound.stops.length?'outbound':'inbound';
  const fallbackDay=cityDay();const day=(['weekday','saturday','sunday'].includes(params.get('day')||'')?params.get('day'):fallbackDay) as DayKey;
  const current=journey[direction];const schedule=current[day];const times=departureTimes(schedule.times)||[];
  const index=Number(params.get('stop')??-1);const selectedStop=Number.isInteger(index)&&index>=0?current.stops[index]:undefined;
  return <article className="transport-route"><div className="transport-detail-heading"><span className="transport-number">{route.route_number}</span><div><h2>{route.route_name}</h2><p>{say('Проверено редакцией','Редакция тексерген')}: {route.verified_at}</p></div></div>
    {notices.map(n=><p className="transport-notice" key={n.id}>{n.message}</p>)}
    <div className="transport-directions" aria-label={say('Направление','Бағыт')}>{(['outbound','inbound']as const).map(d=><button key={d} aria-pressed={direction===d} onClick={()=>{change('direction',d);}}><ArrowLeftRight size={16}/><span>{d==='outbound'?say('Прямое направление','Тура бағыт'):say('Обратное направление','Кері бағыт')}<small>{journey[d].stops.length>=2?`${journey[d].stops[0]} → ${journey[d].stops.at(-1)}`:say('Остановки уточняются','Аялдамалар нақтылануда')}</small></span></button>)}</div>
    <section className="transport-stop-section"><h3>{say('Остановки по порядку','Аялдамалар ретімен')} · {current.stops.length}</h3><p className="transport-note">{say('Выберите свою остановку в списке.','Тізімнен өз аялдамаңызды таңдаңыз.')}</p>{current.stops.length?<ol className="transport-stops">{current.stops.map((stop,i)=><li key={i}><button aria-pressed={selectedStop!==undefined&&i===index} onClick={()=>change('stop',String(i))}><span>{i+1}</span><strong>{stop}</strong>{(i===0||i===current.stops.length-1)&&<small>{i===0?say('Отправление','Жөнелту'):say('Конечная','Соңғы аялдама')}</small>}</button></li>)}</ol>:<p className="transport-empty">{say('Это направление ещё не заполнено. Обратный путь может отличаться от прямого.','Бұл бағыт әлі толтырылмаған. Кері жол тура бағыттан өзгеше болуы мүмкін.')}</p>}</section>
    <section className="transport-schedule"><h3><Clock size={18}/>{say('Расписание отправлений','Жөнелту кестесі')}</h3><div className="transport-days">{([['weekday','Пн–Пт','Дс–Жм'],['saturday','Суббота','Сенбі'],['sunday','Воскресенье','Жексенбі']]as const).map(([value,ru,kk])=><button key={value} aria-pressed={day===value} onClick={()=>change('day',value)}>{say(ru,kk)}</button>)}</div>
      {current.stops.length>0&&<p className="transport-origin">{say('От остановки','Аялдамадан')}: <strong>{current.stops[0]}</strong></p>}
      {selectedStop&&index>0&&<p className="transport-notice">{say('Ваша остановка','Сіздің аялдамаңыз')}: <strong>{selectedStop}</strong>. {say('Время ниже относится к отправлению от первой остановки. Прибытие сюда не рассчитано.','Төмендегі уақыт бірінші аялдамадан жөнелтуге қатысты. Мұнда келу уақыты есептелмеген.')}</p>}
      {schedule.not_running?<p className="transport-empty">{say('В этот день рейсов нет','Бұл күні рейстер жоқ')}</p>:times.length?<><p className="transport-note">{say('По расписанию · время Караганды','Кесте бойынша · Қарағанды уақыты')}</p><div className="transport-times">{times.map(time=><time key={time}>{time}</time>)}</div></>:schedule.first&&schedule.last?<><dl className="transport-frequency"><div><dt>{say('Первый рейс','Алғашқы рейс')}</dt><dd>{schedule.first}</dd></div><div><dt>{say('Последний рейс','Соңғы рейс')}</dt><dd>{schedule.last}</dd></div><div><dt>{say('Интервал','Аралық')}</dt><dd>{schedule.interval||say('Не указан','Көрсетілмеген')}</dd></div></dl><p className="transport-note">{say('Время Караганды. Интервал не является точным временем прибытия.','Қарағанды уақыты. Аралық нақты келу уақытын білдірмейді.')}{schedule.last<schedule.first&&' '+say('Последний рейс — после полуночи.','Соңғы рейс — түн ортасынан кейін.')}</p></>:<p className="transport-empty">{say('Расписание на этот день уточняется','Бұл күннің кестесі нақтылануда')}</p>}
    </section>{route.description&&<p className="transport-note">{route.description}</p>}<div className="transport-source"><a href={httpsLink(route.source_url)} target="_blank" rel="noopener noreferrer">{say('Источник расписания','Кесте дереккөзі')} ↗</a>{httpsLink(route.map_url)&&<a href={httpsLink(route.map_url)} target="_blank" rel="noopener noreferrer">{say('Маршрут на карте','Картадағы бағыт')} ↗</a>}<Link to="/report-problem">{say('Сообщить об ошибке','Қате туралы хабарлау')}</Link></div>
  </article>;
}
