import {test,expect,type Page} from '@playwright/test';
import {newJourney,departureTimes,journeyError,verifiedRoute,routeMatches} from '../src/lib/transportSchedule';
const journey=newJourney();journey.outbound.stops=['Тестовая конечная А','Тестовая школа','Тестовая конечная Б'];journey.inbound.stops=['Тестовая конечная Б','Тестовый рынок','Тестовая конечная А'];journey.outbound.weekday.times='06:10, 06:40, 07:15';journey.inbound.weekday.first='23:00';journey.inbound.weekday.last='01:30';journey.inbound.weekday.interval='30 мин';journey.outbound.sunday.not_running=true;
const route={id:1,route_number:'Т1',route_name:'Тестовая конечная А — Тестовая конечная Б',is_active:true,source_url:'https://example.org/schedule',verified_at:'2026-09-12',journey_json:JSON.stringify(journey)};
async function setup(page:Page){const state={routes:[{...route},{...route,id:2,route_number:'Т2',source_url:'',journey_json:''}],notices:[{id:1,route_id:null,message:'Тестовое общее объявление',is_active:true}],writes:0};
 await page.addInitScript(()=>{localStorage.setItem('app_lang','ru');localStorage.setItem('_sp924_token','test-admin');localStorage.setItem('token','test-admin');});
 await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());
 await page.route('**/api/**',async r=>{const path=new URL(r.request().url()).pathname;let json:unknown={items:[],total:0};if(path.includes('verify-session'))json={valid:true,username:'test'};
  if(path.includes('/entities/bus_routes')){if(r.request().method()==='POST'){state.writes++;const raw=r.request().postDataJSON();const added={id:99,...(raw.data||raw)};state.routes.push(added);json=added;}else if(r.request().method()==='PUT'){state.writes++;const raw=r.request().postDataJSON();const selected=state.routes.find(s=>String(s.id)===path.split('/').pop())!;Object.assign(selected,raw.data||raw);json=selected;}else json={items:state.routes,total:state.routes.length};}
  if(path.includes('/entities/bus_notifications'))json={items:state.notices,total:state.notices.length};await r.fulfill({json});});return state;
}
test('timetable helpers never infer arrival or reverse stops',()=>{expect(departureTimes('06:10 06:40')).toEqual(['06:10','06:40']);expect(departureTimes('25:00')).toBeNull();expect(departureTimes('06:00,06:00')).toBeNull();expect(verifiedRoute(route)).toBe(true);expect(verifiedRoute({...route,source_url:''})).toBe(false);expect(routeMatches(route,'рынок')).toBe(true);expect(routeMatches(route,'рынок аэропорт')).toBe(false);expect(journeyError(journey)).toBe('');});
test('bus selection shows direction-specific stops and terminal departures',async({page},info)=>{await setup(page);await page.goto('/transport?route=1&day=weekday');await expect(page.getByRole('heading',{name:route.route_name,exact:true})).toBeVisible();await expect(page.locator('.transport-stops strong')).toHaveText(journey.outbound.stops);await expect(page.locator('.transport-times time')).toHaveText(['06:10','06:40','07:15']);await expect(page.getByText('На линии',{exact:true})).toHaveCount(0);await expect(page.getByText('Тестовое общее объявление')).toHaveCount(1);await page.getByRole('button',{name:/2 Тестовая школа/}).click();await expect(page.getByText(/Прибытие сюда не рассчитано/)).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('transport.png'),fullPage:true});});
test('return direction is independent and clears selected stop',async({page})=>{await setup(page);await page.goto('/transport?route=1&day=weekday&stop=1');await page.getByRole('button',{name:/Обратное направление/}).click();await expect(page.locator('.transport-stops strong')).toHaveText(journey.inbound.stops);await expect(page.getByText(/после полуночи/)).toBeVisible();expect(new URL(page.url()).searchParams.has('stop')).toBe(false);await expect(page.locator('.transport-times time')).toHaveCount(0);await page.reload();await expect(page.locator('.transport-stops strong')).toHaveText(journey.inbound.stops);});
test('missing timetable differs from no service and search works by stop',async({page})=>{await setup(page);await page.goto('/transport?route=1&day=saturday');await expect(page.getByText('Расписание на этот день уточняется',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Воскресенье',exact:true}).click();await expect(page.getByText('В этот день рейсов нет',{exact:true})).toBeVisible();await page.getByRole('textbox',{name:'Номер автобуса или остановка'}).fill('рынок');await expect(page.locator('.transport-route-list>button')).toHaveCount(1);await page.getByRole('textbox',{name:'Номер автобуса или остановка'}).fill('несуществующая');await expect(page.getByRole('heading',{name:'Автобус или остановка не найдены'})).toBeVisible();});
test('unverified legacy routes are not advertised',async({page})=>{const state=await setup(page);state.routes=[{...route,source_url:''}];await page.goto('/transport');await expect(page.getByRole('heading',{name:'Расписания проходят проверку'})).toBeVisible();await expect(page.getByRole('link',{name:/ONAY/})).toHaveAttribute('href','https://karaganda.onay.kz/ru');await expect(page.locator('.transport-route-list>button')).toHaveCount(0);});
test('admin edits stops and exact departures without fabricated defaults',async({page})=>{const state=await setup(page);await page.goto('/admin?tab=transport');await page.getByRole('button',{name:'Добавить автобус',exact:true}).click();await page.getByLabel('Номер автобуса *',{exact:true}).fill('Т9');await page.getByLabel('Название маршрута *',{exact:true}).fill('Тестовый новый автобус');await page.getByLabel('Остановки по порядку',{exact:true}).fill('Тестовая А\nТестовая Б');await expect(page.getByLabel('Точные отправления',{exact:true})).toHaveValue('');await page.getByLabel('Точные отправления',{exact:true}).fill('06:20, 06:50');await page.getByRole('button',{name:'Сохранить черновик'}).click();await expect(page.getByRole('status')).toContainText('Маршрут сохранён');expect(state.writes).toBe(1);await page.getByRole('button',{name:'Редактировать автобус Т9'}).click();await expect(page.getByLabel('Остановки по порядку',{exact:true})).toHaveValue('Тестовая А\nТестовая Б');await page.getByLabel('Опубликовать после проверки').check();await page.getByRole('button',{name:'Сохранить и опубликовать'}).click();await expect(page.getByRole('alert')).toContainText('Для публикации');expect(state.writes).toBe(1);await page.getByLabel('Источник маршрута и расписания',{exact:true}).fill('https://example.org/source');await page.getByLabel('Дата проверки',{exact:true}).fill('2026-09-12');await page.getByRole('button',{name:'Сохранить и опубликовать'}).click();await expect(page.getByRole('status')).toContainText('Маршрут сохранён');await page.goto('/transport?route=99&day=weekday');await expect(page.locator('.transport-times time')).toHaveText(['06:20','06:50']);});
test('dark theme and enlarged text remain readable',async({page},info)=>{await setup(page);await page.goto('/transport?route=1&day=weekday');await expect(page.locator('.transport-times time')).toHaveCount(3);await page.evaluate(()=>{document.documentElement.classList.add('dark');document.documentElement.style.fontSize='20px';});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('transport-dark.png'),fullPage:true});});
