"""auto update

Revision ID: 1b82ef827dbc
Revises: 7cd6c8aa864f
Create Date: 2026-03-15 09:05:16.714848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b82ef827dbc'
down_revision: Union[str, Sequence[str], None] = '7cd6c8aa864f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('gallery_images', sa.String(), nullable=True))
    op.alter_column('complaints', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('news', sa.Column('gallery_images', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'gallery_images')
    op.alter_column('complaints', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('complaints', 'gallery_images')
    # ### end Alembic commands ###