"""auto update

Revision ID: 45404b0077e1
Revises: 910c923a3ac7
Create Date: 2026-04-21 09:55:43.941250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45404b0077e1'
down_revision: Union[str, Sequence[str], None] = '910c923a3ac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('categories', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('categories', 'cat_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('food_items', 'available_in_park',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('inspectors', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('inspectors', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('inspectors', 'streets',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inspectors', 'streets',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('inspectors', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('inspectors', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('food_items', 'available_in_park',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('categories', 'cat_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('categories', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###