"""auto update

Revision ID: 50e38e169f32
Revises: 9ce156cd19ab
Create Date: 2026-03-22 10:16:10.905997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50e38e169f32'
down_revision: Union[str, Sequence[str], None] = '9ce156cd19ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_modifier_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('food_item_id', sa.Integer(), nullable=False),
    sa.Column('modifier_group_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_modifier_groups_id'), 'item_modifier_groups', ['id'], unique=False)
    op.create_table('modifier_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('min_select', sa.Integer(), nullable=True),
    sa.Column('max_select', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modifier_groups_id'), 'modifier_groups', ['id'], unique=False)
    op.create_table('modifier_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modifier_options_id'), 'modifier_options', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modifier_options_id'), table_name='modifier_options')
    op.drop_table('modifier_options')
    op.drop_index(op.f('ix_modifier_groups_id'), table_name='modifier_groups')
    op.drop_table('modifier_groups')
    op.drop_index(op.f('ix_item_modifier_groups_id'), table_name='item_modifier_groups')
    op.drop_table('item_modifier_groups')
    # ### end Alembic commands ###