"""auto update

Revision ID: 66cc3f73ee5a
Revises: 1b82ef827dbc
Create Date: 2026-03-15 09:32:52.944621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66cc3f73ee5a'
down_revision: Union[str, Sequence[str], None] = '1b82ef827dbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('status', sa.String(), nullable=True))
    op.alter_column('banners', 'title',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('banners', 'banner_title')
    op.drop_column('banners', 'banner_type')
    op.drop_column('banners', 'banner_text')
    op.add_column('complaints', sa.Column('complaint_video', sa.String(), nullable=True))
    op.alter_column('jobs', 'employer',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jobs', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('masters', sa.Column('active', sa.Boolean(), nullable=True))
    op.drop_column('masters', 'verified')
    op.drop_column('masters', 'services')
    op.drop_column('masters', 'experience_years')
    op.drop_column('masters', 'reviews_count')
    op.drop_column('masters', 'available_today')
    op.add_column('news', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'status')
    op.add_column('masters', sa.Column('available_today', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('masters', sa.Column('reviews_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('masters', sa.Column('experience_years', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('masters', sa.Column('services', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('masters', sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('masters', 'active')
    op.alter_column('jobs', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jobs', 'employer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('complaints', 'complaint_video')
    op.add_column('banners', sa.Column('banner_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('banners', sa.Column('banner_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('banners', sa.Column('banner_title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('banners', 'title',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("''::character varying"),
               existing_nullable=False)
    op.drop_column('announcements', 'status')
    # ### end Alembic commands ###