"""auto update

Revision ID: 910c923a3ac7
Revises: 933e0c788db2
Create Date: 2026-04-06 09:56:54.347729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '910c923a3ac7'
down_revision: Union[str, Sequence[str], None] = '933e0c788db2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couriers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('pin_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_couriers_id'), 'couriers', ['id'], unique=False)
    op.create_table('park_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_items', sa.String(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('customer_phone', sa.String(), nullable=False),
    sa.Column('park_point_id', sa.Integer(), nullable=True),
    sa.Column('park_point_name', sa.String(), nullable=False),
    sa.Column('park_lat', sa.Float(), nullable=True),
    sa.Column('park_lng', sa.Float(), nullable=True),
    sa.Column('park_note', sa.String(), nullable=False),
    sa.Column('user_geolocation', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('assigned_courier_id', sa.Integer(), nullable=True),
    sa.Column('courier_name', sa.String(), nullable=True),
    sa.Column('delivery_queue_position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_park_orders_id'), 'park_orders', ['id'], unique=False)
    op.create_table('park_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_park_points_id'), 'park_points', ['id'], unique=False)
    op.alter_column('inspectors', 'is_leadership',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('inspectors', 'leadership_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inspectors', 'leadership_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('inspectors', 'is_leadership',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.drop_index(op.f('ix_park_points_id'), table_name='park_points')
    op.drop_table('park_points')
    op.drop_index(op.f('ix_park_orders_id'), table_name='park_orders')
    op.drop_table('park_orders')
    op.drop_index(op.f('ix_couriers_id'), table_name='couriers')
    op.drop_table('couriers')
    # ### end Alembic commands ###