"""auto update

Revision ID: 933e0c788db2
Revises: b4262076980f
Create Date: 2026-03-31 11:07:43.717413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '933e0c788db2'
down_revision: Union[str, Sequence[str], None] = 'b4262076980f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bus_notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bus_notifications_id'), 'bus_notifications', ['id'], unique=False)
    op.create_table('bus_routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_number', sa.String(), nullable=False),
    sa.Column('route_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('first_departure_weekday', sa.String(), nullable=True),
    sa.Column('last_departure_weekday', sa.String(), nullable=True),
    sa.Column('interval_weekday', sa.String(), nullable=True),
    sa.Column('first_departure_weekend', sa.String(), nullable=True),
    sa.Column('last_departure_weekend', sa.String(), nullable=True),
    sa.Column('interval_weekend', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bus_routes_id'), 'bus_routes', ['id'], unique=False)
    op.create_table('bus_stops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('stop_name', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('stop_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bus_stops_id'), 'bus_stops', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bus_stops_id'), table_name='bus_stops')
    op.drop_table('bus_stops')
    op.drop_index(op.f('ix_bus_routes_id'), table_name='bus_routes')
    op.drop_table('bus_routes')
    op.drop_index(op.f('ix_bus_notifications_id'), table_name='bus_notifications')
    op.drop_table('bus_notifications')
    # ### end Alembic commands ###