"""auto update

Revision ID: 9ce156cd19ab
Revises: cc186b3906d8
Create Date: 2026-03-22 09:35:57.122469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ce156cd19ab'
down_revision: Union[str, Sequence[str], None] = 'cc186b3906d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspectors', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('inspectors', sa.Column('lng', sa.Float(), nullable=True))
    op.add_column('inspectors', sa.Column('boundary_coords', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspectors', 'boundary_coords')
    op.drop_column('inspectors', 'lng')
    op.drop_column('inspectors', 'lat')
    # ### end Alembic commands ###