"""auto update

Revision ID: ab6e51b6af51
Revises: 50e38e169f32
Create Date: 2026-03-23 02:14:47.569060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab6e51b6af51'
down_revision: Union[str, Sequence[str], None] = '50e38e169f32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homepage_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('masters_count', sa.Integer(), nullable=True),
    sa.Column('ads_count', sa.Integer(), nullable=True),
    sa.Column('cafes_count', sa.Integer(), nullable=True),
    sa.Column('is_auto', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homepage_stats_id'), 'homepage_stats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_homepage_stats_id'), table_name='homepage_stats')
    op.drop_table('homepage_stats')
    # ### end Alembic commands ###