"""auto update

Revision ID: b4262076980f
Revises: f80eb8c6a405
Create Date: 2026-03-31 10:31:35.272802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4262076980f'
down_revision: Union[str, Sequence[str], None] = 'f80eb8c6a405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_check',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_check_id'), 'health_check', ['id'], unique=False)
    op.alter_column('food_items', 'photo_locked',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('food_items', 'photo_locked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.drop_index(op.f('ix_health_check_id'), table_name='health_check')
    op.drop_table('health_check')
    # ### end Alembic commands ###