"""auto update

Revision ID: cc186b3906d8
Revises: 8765d168e422
Create Date: 2026-03-22 08:50:32.892924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc186b3906d8'
down_revision: Union[str, Sequence[str], None] = '8765d168e422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspectors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('precinct_number', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('whatsapp', sa.String(), nullable=True),
    sa.Column('streets', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspectors_id'), 'inspectors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inspectors_id'), table_name='inspectors')
    op.drop_table('inspectors')
    # ### end Alembic commands ###