"""auto update

Revision ID: ceca3d7bbddc
Revises: a3e0af583a54
Create Date: 2026-03-17 09:58:10.064638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ceca3d7bbddc'
down_revision: Union[str, Sequence[str], None] = 'a3e0af583a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('announcements', 'ann_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('announcements', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('announcements', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('announcements', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('announcements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('banners', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('banners', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('banners', 'sort_order')
    op.alter_column('become_master_requests', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('become_master_requests', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('become_master_requests', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('become_master_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('complaints', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('complaints', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('complaints', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('complaints', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('complaints', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('directory_entries', 'entry_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('directory_entries', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('directory_entries', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('directory_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('jobs', 'job_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jobs', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jobs', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('master_requests', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('master_requests', 'problem_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('master_requests', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('master_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('masters', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('masters', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('masters', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('masters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('masters', 'active')
    op.alter_column('news', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('news', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('news', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('news', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('news', 'status')
    op.alter_column('question_answers', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('question_answers', 'answer_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('question_answers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('questions', 'question_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('questions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'created_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('questions', 'question_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('question_answers', 'created_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('question_answers', 'answer_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('question_answers', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('news', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('news', 'created_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('news', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('news', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('news', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('masters', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('masters', 'created_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('masters', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('masters', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('masters', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('master_requests', 'created_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('master_requests', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('master_requests', 'problem_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('master_requests', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jobs', 'created_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('jobs', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jobs', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jobs', 'job_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('directory_entries', 'created_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('directory_entries', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('directory_entries', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('directory_entries', 'entry_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('complaints', 'created_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('complaints', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('complaints', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('complaints', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('complaints', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('become_master_requests', 'created_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('become_master_requests', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('become_master_requests', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('become_master_requests', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('banners', sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('banners', 'created_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('banners', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('announcements', 'created_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('announcements', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('announcements', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('announcements', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('announcements', 'ann_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###