"""Global customer and business-scoped CRM; preserve ambiguous legacy records."""
from alembic import op
import sqlalchemy as sa
revision = 'dam20261001b_crm'
down_revision = 'dam20261001_payment_lifecycle'
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.current_timestamp(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('normalized_phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.current_timestamp(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.current_timestamp(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_customers_normalized_phone'), 'customers', ['normalized_phone'], unique=True)
    op.create_table('customer_identities',
    sa.Column('normalized_phone', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('normalized_phone')
    )
    op.create_index(op.f('ix_customer_identities_customer_id'), 'customer_identities', ['customer_id'], unique=False)
    op.create_table('business_customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('first_source', sa.String(length=20), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.func.current_timestamp(), nullable=True),
    sa.Column('marketing_opt_in', sa.Boolean(), nullable=False),
    sa.Column('transactional_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'customer_id', name='uq_business_customer')
    )
    op.create_index(op.f('ix_business_customers_business_id'), 'business_customers', ['business_id'], unique=False)
    op.create_index(op.f('ix_business_customers_customer_id'), 'business_customers', ['customer_id'], unique=False)
    op.create_table('customer_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('membership_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('actor_role', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.current_timestamp(), nullable=True),
    sa.ForeignKeyConstraint(['membership_id'], ['business_customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_notes_membership_id'), 'customer_notes', ['membership_id'], unique=False)
    op.create_table('business_locations',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('landmark', sa.String(length=500), nullable=False),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('supports_pickup', sa.Boolean(), nullable=False),
    sa.Column('supports_delivery', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_locations_business_id'), 'business_locations', ['business_id'], unique=False)
    op.create_table('customer_migration_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channel_confirmations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('message_key', sa.String(length=255), nullable=False),
    sa.Column('quote_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['food_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_key')
    )
    # ### end Alembic commands ###
    op.add_column('users', sa.Column('phone_verified_at', sa.DateTime(timezone=True)))
    op.add_column('food_restaurants', sa.Column('business_id', sa.String(64)))
    op.create_index('ix_food_restaurants_business_id','food_restaurants',['business_id'])
    op.add_column('food_orders', sa.Column('business_id', sa.String(64)))
    op.add_column('food_orders', sa.Column('customer_id', sa.String(255)))
    op.create_index('ix_food_orders_business_id','food_orders',['business_id'])
    op.create_index('ix_food_orders_customer_id','food_orders',['customer_id'])
    op.create_index('ix_food_orders_business_customer','food_orders',['business_id','customer_id','id'])
    seed_legacy()


def seed_legacy():
    import uuid, re, unicodedata
    from collections import defaultdict
    bind=op.get_bind()
    tables=sa.MetaData()
    tables.reflect(bind=bind,only=['businesses','customers','customer_identities','business_customers','business_locations','customer_migration_issues','users','food_restaurants','food_orders'])
    t=tables.tables
    def phone(v):
        d=re.sub(r'[^0-9]','',str(v or ''))
        if len(d)==10: d='7'+d
        if len(d)==11 and d[0]=='8': d='7'+d[1:]
        return '+'+d if len(d)==11 and d[0]=='7' else None
    def brand(name,key):
        if key: return key=='dam_alem'
        n=''.join(c for c in unicodedata.normalize('NFKD',(name or '').lower()) if not unicodedata.combining(c))
        return re.sub(r'[\s-]|2\.0','',n) in {'damalem','дамалем','алемфуд','alemfood','damәлемі','дәмәлемі'}
    businesses={'dam_alem'}
    bind.execute(t['businesses'].insert().values(id='dam_alem',slug='dam_alem',name='DÄM ALEM 2.0',active=True))
    rests={}
    for r in bind.execute(sa.select(t['food_restaurants'])).mappings():
        bid='dam_alem' if brand(r['name'],r.get('merchant_key')) else 'restaurant-'+str(r['id'])
        if bid not in businesses:
            bind.execute(t['businesses'].insert().values(id=bid,slug=bid,name=r['name'] or bid,active=True));businesses.add(bid)
        rests[r['id']]=bid
        bind.execute(t['food_restaurants'].update().where(t['food_restaurants'].c.id==r['id']).values(business_id=bid))
    bind.execute(t['business_locations'].insert().values(id='dam_alem:main',business_id='dam_alem',name='DÄM ALEM 2.0',address='Парк Железнодорожников',landmark='Ориентир: бывший фонтан',supports_pickup=True,supports_delivery=True,active=True))
    users=defaultdict(list)
    for u in bind.execute(sa.select(t['users'])).mappings():
        if phone(u['phone']): users[phone(u['phone'])].append(u)
        if u.get('bonus_balance'):
            bind.execute(t['customer_migration_issues'].insert().values(kind='LEGACY_BALANCE_REVIEW',details={'user_id':u['id'],'amount':str(u['bonus_balance']),'reason':'Legacy platform balance has no reliable business allocation; preserved, never silently reassigned.'}))
    verified=set()
    if 'phone_verifications' in sa.inspect(bind).get_table_names():
        for r in bind.execute(sa.text('SELECT phone FROM phone_verifications WHERE is_verified = true')).mappings():
            if phone(r['phone']): verified.add(phone(r['phone']))
    customer_by_phone={};members=set()
    def customer(number,name):
        if number in customer_by_phone: return customer_by_phone[number]
        cid=str(uuid.uuid4());rows=users.get(number,[])
        uid=rows[0]['id'] if len(rows)==1 and number in verified else None
        at=sa.func.now() if uid else None
        state='REVIEW' if len(rows)>1 else 'NORMAL'
        bind.execute(t['customers'].insert().values(id=cid,normalized_phone=number,name=name or (rows[0]['name'] if rows else '') or 'Клиент',user_id=uid,verified_at=at,state=state))
        bind.execute(t['customer_identities'].insert().values(normalized_phone=number,customer_id=cid,verified_at=at))
        if uid: bind.execute(t['users'].update().where(t['users'].c.id==uid).values(phone_verified_at=at))
        if len(rows)>1:
            bind.execute(t['customer_migration_issues'].insert().values(kind='DUPLICATE_PHONE',details={'customer_id':cid,'user_ids':[r['id'] for r in rows],'reason':'No accounts merged or linked automatically'}))
        customer_by_phone[number]=cid
        return cid
    for o in bind.execute(sa.select(t['food_orders']).order_by(t['food_orders'].c.id)).mappings():
        number=phone(o['customer_phone']);bid=rests.get(o['restaurant_id'])
        if not bid and brand(o['restaurant_name'],None): bid='dam_alem'
        if not number or not bid:
            bind.execute(t['customer_migration_issues'].insert().values(kind='ORDER_IDENTITY_REVIEW',details={'order_id':o['id'],'reason':'Invalid phone or unknown business; original order preserved'}));continue
        cid=customer(number,o['customer_name'])
        bind.execute(t['food_orders'].update().where(t['food_orders'].c.id==o['id']).values(customer_id=cid,business_id=bid))
        if (bid,cid) not in members:
            bind.execute(t['business_customers'].insert().values(id=str(uuid.uuid4()),business_id=bid,customer_id=cid,first_source=o.get('order_source') or 'app',marketing_opt_in=False,transactional_enabled=True));members.add((bid,cid))
    for number,rows in users.items(): customer(number,rows[0]['name'])


def downgrade():
    raise RuntimeError('CRM identity history is retained. Use a verified backup for rollback.')
