"""Extend the existing bonus ledger; preserve legacy balances and history.

Only Alembic applies this schema. No startup schema repair is added.
"""
from alembic import op
import sqlalchemy as sa

revision = 'dam20261002_loyalty'
down_revision = 'dam20261001b_crm'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    with op.batch_alter_table('users') as batch:
        batch.alter_column('bonus_balance', existing_type=sa.Float(), type_=sa.Numeric(14, 2))
        batch.add_column(sa.Column('bonus_debt', sa.Numeric(14, 2), nullable=False, server_default='0'))
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonus_policy',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bonus_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('bonus_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('bonus_debt', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('referral_code', sa.String(length=48), nullable=False),
    sa.Column('welcome_order_id', sa.Integer(), nullable=True),
    sa.Column('legacy_welcome', sa.Integer(), nullable=False),
    sa.Column('initialized', sa.Integer(), nullable=False),
    sa.CheckConstraint('bonus_balance >= 0 AND bonus_debt >= 0', name='ck_bonus_account_nonnegative'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['id'], ['business_customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'customer_id', name='uq_bonus_business_customer'),
    sa.UniqueConstraint('referral_code')
    )
    op.create_index(op.f('ix_bonus_members_business_id'), 'bonus_members', ['business_id'], unique=False)
    op.create_index(op.f('ix_bonus_members_customer_id'), 'bonus_members', ['customer_id'], unique=False)
    # ### end Alembic commands ###
    with op.batch_alter_table('bonuses') as batch:
        batch.alter_column('user_id', existing_type=sa.String(255), nullable=True)
        batch.add_column(sa.Column('account_id', sa.String(36)))
        batch.add_column(sa.Column('business_id', sa.String(64)))
        batch.add_column(sa.Column('customer_id', sa.String(36)))
        batch.create_foreign_key('fk_bonus_account','bonus_members',['account_id'],['id'])
        batch.create_foreign_key('fk_bonus_business','businesses',['business_id'],['id'])
        batch.create_foreign_key('fk_bonus_customer','customers',['customer_id'],['id'])
        batch.create_index('ix_bonuses_account_id',['account_id'])
        batch.create_index('ix_bonuses_business_id',['business_id'])
        batch.create_index('ix_bonuses_customer_id',['customer_id'])
        batch.alter_column('points', existing_type=sa.Float(), type_=sa.Numeric(14, 2))
        batch.add_column(sa.Column('kind', sa.String(32), nullable=False, server_default='LEGACY'))
        batch.add_column(sa.Column('order_id', sa.Integer()))
        batch.add_column(sa.Column('balance_before', sa.Numeric(14, 2)))
        batch.add_column(sa.Column('balance_after', sa.Numeric(14, 2)))
        batch.add_column(sa.Column('expires_at', sa.DateTime(timezone=True)))
        batch.add_column(sa.Column('created_by', sa.String(255)))
        batch.add_column(sa.Column('actor_role', sa.String(40)))
        batch.add_column(sa.Column('details', sa.JSON()))
        batch.add_column(sa.Column('idempotency_key', sa.String(255)))
        batch.create_unique_constraint('uq_bonuses_idempotency_key', ['idempotency_key'])
        batch.create_index('ix_bonuses_order_id', ['order_id'])
    op.add_column('food_orders', sa.Column('loyalty_snapshot', sa.JSON()))
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonus_lots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('remaining', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('remaining >= 0', name='ck_bonus_lot_remaining'),
    sa.ForeignKeyConstraint(['account_id'], ['bonus_members.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['bonuses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id')
    )
    op.create_index(op.f('ix_bonus_lots_account_id'), 'bonus_lots', ['account_id'], unique=False)
    op.create_index(op.f('ix_bonus_lots_expires_at'), 'bonus_lots', ['expires_at'], unique=False)
    op.create_table('bonus_allocations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('debit_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['debit_id'], ['bonuses.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['bonus_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bonus_allocations_debit_id'), 'bonus_allocations', ['debit_id'], unique=False)
    op.create_table('bonus_referrals',
    sa.Column('referred_id', sa.String(length=255), nullable=False),
    sa.Column('referrer_id', sa.String(length=255), nullable=False),
    sa.Column('qualified_order_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.current_timestamp(), nullable=True),
    sa.CheckConstraint('referred_id <> referrer_id', name='ck_bonus_no_self_referral'),
    sa.ForeignKeyConstraint(['referred_id'], ['bonus_members.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['bonus_members.id'], ),
    sa.PrimaryKeyConstraint('referred_id'),
    sa.UniqueConstraint('qualified_order_id')
    )
    op.create_index(op.f('ix_bonus_referrals_referrer_id'), 'bonus_referrals', ['referrer_id'], unique=False)
    op.create_table('bonus_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_key', sa.String(length=255), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.current_timestamp(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['bonus_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_key')
    )
    # ### end Alembic commands ###
    # Existing completed buyers cannot claim a second first-order offer.
    import secrets
    m=sa.MetaData();m.reflect(bind=bind,only=['business_customers','bonus_members','food_orders'])
    for row in bind.execute(sa.select(m.tables['business_customers'])).mappings():
        orders=m.tables['food_orders']
        prior=bind.execute(sa.select(orders.c.id).where(orders.c.customer_id==row['customer_id'],orders.c.business_id==row['business_id'],orders.c.status=='done',orders.c.payment_status=='paid').limit(1)).first()
        bind.execute(m.tables['bonus_members'].insert().values(id=row['id'],business_id=row['business_id'],customer_id=row['customer_id'],referral_code=secrets.token_urlsafe(18),initialized=1,legacy_welcome=int(bool(prior)),bonus_balance=0,bonus_debt=0,enabled=1))
    if bind.dialect.name == 'postgresql':
        op.execute("CREATE FUNCTION protect_bonus_history() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Bonus history is append-only'; END $$")
        op.execute('CREATE TRIGGER bonuses_immutable BEFORE UPDATE OR DELETE ON bonuses FOR EACH ROW EXECUTE FUNCTION protect_bonus_history()')
    elif bind.dialect.name == 'sqlite':
        for verb in ('UPDATE', 'DELETE'):
            op.execute(f"CREATE TRIGGER bonuses_no_{verb.lower()} BEFORE {verb} ON bonuses BEGIN SELECT RAISE(ABORT, 'Bonus history is append-only'); END")


def downgrade():
    raise RuntimeError('Loyalty financial history must not be deleted. Restore a verified backup instead.')
