"""auto update

Revision ID: f80eb8c6a405
Revises: e247de1025eb
Create Date: 2026-03-23 03:07:02.378860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f80eb8c6a405'
down_revision: Union[str, Sequence[str], None] = 'e247de1025eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frontpad_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('setting_key', sa.String(), nullable=False),
    sa.Column('setting_value', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frontpad_settings_id'), 'frontpad_settings', ['id'], unique=False)
    op.create_table('frontpad_sync_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sync_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('products_synced', sa.Integer(), nullable=True),
    sa.Column('categories_synced', sa.Integer(), nullable=True),
    sa.Column('errors', sa.String(), nullable=True),
    sa.Column('started_at', sa.String(), nullable=True),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frontpad_sync_log_id'), 'frontpad_sync_log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_frontpad_sync_log_id'), table_name='frontpad_sync_log')
    op.drop_table('frontpad_sync_log')
    op.drop_index(op.f('ix_frontpad_settings_id'), table_name='frontpad_settings')
    op.drop_table('frontpad_settings')
    # ### end Alembic commands ###