"""auto update

Revision ID: f8de77210efe
Revises: bba94203687d
Create Date: 2026-03-15 10:20:26.026992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8de77210efe'
down_revision: Union[str, Sequence[str], None] = 'bba94203687d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcements', 'gallery_images')
    op.drop_column('banners', 'banner_type')
    op.drop_column('banners', 'banner_text')
    op.drop_column('jobs', 'status')
    op.drop_column('jobs', 'image_url')
    op.drop_column('jobs', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('status', sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True))
    op.add_column('banners', sa.Column('banner_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('banners', sa.Column('banner_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('announcements', sa.Column('gallery_images', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###